### ISSUE TITLE
Pipelines unable to use internal registry images created during collection curation

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-pipelines#101]
@bconey commented on [Tue Oct 29 2019](https://github.com/kabanero-io/kabanero-foundation/issues/117)

If a user chooses to use their internal registry for pushing images of the stack (java MicroProfie) as part of collection curation, pipeline is still looking at docker hub for the image. If image does not exist in docker hub, pipeline run will fail.  There is no way to tell the pipeline to use the internal registry location to find the stack images.

So in the following example of the assemble-extract step it shows `Pulling docker image kabanero/java-microprofile:0.2` it should be using image `java-microprofile    docker-registry.default.svc:5000/kabanero/java-microprofile`

<img width="1482" alt="image" src="https://user-images.githubusercontent.com/31766760/67785360-712c6b00-fa43-11e9-9a5c-99548b95a885.png">

**Comment by marikaj123** [comment]
@mtamboli and @gecock - Have you received from developement what you need to verify and close this issue?

**Comment by mtamboli** [comment]
@marikaj123 No, I have not seen it yet.

**Comment by kvijai82** [comment]
We don't have a solution for this yet.  Worked with @aadeshpa and @bconey to test out and investigate possible solutions.  Discussing options with @stephenkinder this afternoon to decide on the path to follow and will start working on the implementation after that.

**Comment by marikaj123** [comment]
Actions:
- Deciding on the proposals and solutions by today before can get the issue completed.

**Comment by aadeshpa** [comment]
We have a solution by which we can tell the pipelines to pull the collection image from the internal registry.
We added new ConfigMap for the user to give the internal registry url in the form of external route and for authentication of that registry route we added Kubernetes Secret template .
We are ready with the solution and testing with it in Barabara's openshift 3.11 cluster on IBM cloud with customized twas collection image from internal registry.
We are planning to create pull request with the change.
cc: @marikaj123 @kvijai82 @stephenkinder

**Comment by aadeshpa** [comment]
The pull request created for this fix : https://github.com/kabanero-io/kabanero-pipelines/pull/124

**Comment by aadeshpa** [comment]
The pull request in collections repository : https://github.com/kabanero-io/collections/pull/175

**Comment by kvijai82** [comment]
Fix merged into collections 0.3.0-rc4.  Closing the issue.  If there are further issue, will address in new issues.

**Comment by marikaj123** [comment]
Ashish added the required doc to the pipelines guide that is in a draft state.

**Comment by aadeshpa** [comment]
The pull request for the documentation : https://github.com/aadeshpa/draft-guide-working-with-pipelines/pull/1 
Needs to be reviewed by @kvijai82
