### ISSUE TITLE
Dependent Project upgrade Tekton 0.8 Pipelines

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-pipelines#106]
@kvijai82 commented on [Fri Nov 01 2019](https://github.com/kabanero-io/kabanero-foundation/issues/123)

Would like to investigate if we can pull in tekton 0.8 in the next release (0.4.0) as it contains fixes for a couple of issues we have in pipelines.

**Comment by kaczyns** [comment]
The first gate will be whether the `openshift-pipelines-operator` project pulls in 0.8 from the upstream tekton operator, and publishes it to community-operators.

**Comment by kvijai82** [comment]
Updated in 0.5.0 to pull in tekton 0.8
