### ISSUE TITLE
Creating a PR (no merge) cause the application to be re-deployed

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-pipelines#107]
@gecock commented on [Wed Oct 16 2019](https://github.com/kabanero-io/kabanero-foundation/issues/106)

@mtamboli found the following issue:

The problem is that when a PR is created for an application update in Git repository, it just starts the pipeline run and redeploys on top of the the working application. So basically, this PR was not even reviewed and merged by anyone but it still replaces the existing running application which may cause unwanted changed to be redeployed. It there was a separate deployment for testing this PR, this was fine. 

With lack of eventing, there is not much control. But this behavior should be changed to only redeploy when the PR is merged. No action when PR is created. 

There is a pull request to fix this here -- https://github.com/kabanero-io/kabanero-pipelines/pull/73, but it is blocked on this -- https://github.com/kabanero-io/kabanero-foundation/issues/93 and this https://github.com/kabanero-io/kabanero-foundation/issues/94

---

@gecock commented on [Wed Oct 16 2019](https://github.com/kabanero-io/kabanero-foundation/issues/106#issuecomment-542883739)

@vtereso can you confirm for us that your PR (https://github.com/kabanero-io/kabanero-pipelines/pull/73) will address this situation? If so can you also confirm we cannot merge it until https://github.com/kabanero-io/kabanero-foundation/issues/93 is completed?

---

@anneqm commented on [Wed Oct 16 2019](https://github.com/kabanero-io/kabanero-foundation/issues/106#issuecomment-542889337)

@gecock I believe PR#73 is is also dependent on #94 

---

@vtereso commented on [Wed Oct 16 2019](https://github.com/kabanero-io/kabanero-foundation/issues/106#issuecomment-542889350)

As per the [release page](https://github.com/tektoncd/pipeline/releases), conditions have been available since 0.6, which was the same release the `$()` interpolation syntax was introduced. Within the next release, the `${}` release was deprecated. There were changes to the experimental code to pass new parameters into the pipeline, which are used by the conditional within my PR. So, Tekton 0.6 and 0.7 are both satisfactory, but ultimately the updated experimental code is necessary to pass in the event type. In Tekton 0.5, we would conditionally return before deployment within [this task](https://github.com/kabanero-io/kabanero-pipelines/blob/master/pipelines/incubator/deploy-task.yaml). 

---

@marikaj123 commented on [Wed Oct 16 2019](https://github.com/kabanero-io/kabanero-foundation/issues/106#issuecomment-542889700)

Tekton 0.7 is not for the 0.2 release.

---

@kvijai82 commented on [Wed Oct 16 2019](https://github.com/kabanero-io/kabanero-foundation/issues/106#issuecomment-542890946)

I am planning to experiment with tekton 0.7 next week and can try to see if we can address this issue then but can't get this into 0.2 kab release.  Too many dependency issues to sort out.

---

@gecock commented on [Wed Oct 16 2019](https://github.com/kabanero-io/kabanero-foundation/issues/106#issuecomment-542892759)

Thanks all. Appreciate the info. We will revisit this to verify once all these other issues are resolved.

---

@marikaj123 commented on [Wed Oct 16 2019](https://github.com/kabanero-io/kabanero-foundation/issues/106#issuecomment-542936331)

 @gecock - I am removing the label release-0.2 as you seem to be in agreement with Vijai's comment. 

---

@kvijai82 commented on [Fri Nov 01 2019](https://github.com/kabanero-io/kabanero-foundation/issues/106#issuecomment-548740008)

The long term fix is in the new set of pipelines we are delivering in this release to work with the eventing framework.  We have a pipeline that will only do a build based on PRs and another that will build & push once a PR is merged.  Both of these will not deploy.  Idea here is there will be very specific pipelines for specific triggers.  

Having said that, will see what we can do to fix the issue in the existing build-deploy pipeline.  As of now don't have the conditional path working.

**Comment by marikaj123** [comment]
Actions:
- Experimental pipelines are provided as a temp solution until the eventing will complete.
  For release 0.3.0 can use the temp solution.

**Comment by marikaj123** [comment]
@kvijai82 - Please let us know when the tem solution is provided.  Thank you.

**Comment by kvijai82** [comment]
@marikaj123 We have the solution working in our test env.  @aadeshpa is doing final tests and should have a PR ready by tomorrow.

**Comment by kvijai82** [comment]
@marikaj123 Experimental pipelines are in the 0.3.0 collections.  Don't have the bandwidth to implement the short term conditional logic in the pipeline.  Going to close this out.
