### ISSUE TITLE
Kabanero Collection Validation Pipeline Step should be clearer.

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-pipelines#109]
@stephenkinder commented on [Wed Oct 16 2019](https://github.com/kabanero-io/kabanero-foundation/issues/102)

Users who have not updated their Appsody CLI repo to point at kabanero collections instead of appsody applications are confused about why their builds fail.  This is intentional, and is actually one of the value propositions of Kabanero -- but we should explain that the specific collection they are trying to build is not activated in the Kabanero instance for the triggered Pipeline.  We should describe the collection activation proposition.  @smcclem can help with supplying the text.

---

@nastacio commented on [Wed Oct 16 2019](https://github.com/kabanero-io/kabanero-foundation/issues/102#issuecomment-542710402)

The person who did not have their appsody cli repo updated is likely not the same as the person who will be notified about the problem. In a team where the developer does not manage the pipeline, we would have a pipeline administrator receiving a build breakage alert and implicitly tasked with notifying the application owner.

At that point, some thoughts would be:
1. Pipeline automatically email application owner or last committer? That is, assuming the pipeline even has mechanisms (credentials, pipeline task, clear network path through firewalls) to perform such action.
2. Pipeline admin performs #1 manually...ouch...
3. Creation of a pipeline runs a precheck of credentials and 'alignment' between the application and the pipeline (e.g. app lists an incompatible stack) . Failure still goes back to #1 or #2, but at least it will happen earlier in the process, hopefully before the new git repo is shared with all other developers for regular development.

**Comment by SueChaplain** [comment]
The following guide (in review) tells users how to point at the Kabanero collection hub and specifically calls out that the default Appsody CLI repo does not work with the Kabanero App cluster: https://github.com/kabanero-io/draft-guide-collection-nodejs

We should sweep the rest of the guides and ensure that these also contain this information.

**Comment by SueChaplain** [comment]
@stephenkinder - so in addition to making sure all our guides tell Jane to point only to the enterprise Kabanero collection hub, do we need to talk about how to activate a collection somewhere?? Would the "Working with Collections" Guide make sense (https://github.com/kabanero-io/draft-guide-working-with-collections)??

**Comment by SueChaplain** [comment]
> @smcclem can help with supplying the text.

@smcclem - can you help establish what is required here please? This has been targeted at release-0.3, but unless I get some input from someone it won't happen.

**Comment by kvijai82** [comment]
@SueChaplain I don't know which doc this would fit into best, but we have to convey to Todd that the pipelines will check upfront that the collection that was specified in the .appsody-config.yaml file in the git repo is activated in the cluster the pipeline is running on.  If the collection is not active in the cluster, the pipeline will fail.

We have a working with pipelines guide that was been in review state for a long time.  Maybe we can mention something there?  If there is a Jane guide, might be helpful to tell her also that the she should only be working with collections that Champ has approved and has activated in the clusters where her application will be built and deployed.

@stephenkinder is ^^ what you had in mind or did you want us to improve the failure message in the pipeline itself?  This is the message that we have today

```The Kabanero collection contained in "$stack" is not active on this system and cannot be built.```

Maybe we add the following to it?

```Please review the active collections on this cluster and the stack value in the .appsody-config.yaml in the git repo to resolve this problem.  The stack specified in the .appsody-config.yaml must be one of the active collections in the cluster for the build task of the pipeline to work.```

**Comment by SueChaplain** [comment]
@kvijai82 

>We have a working with pipelines guide that was been in review state for a long time. Maybe we can mention something there?

+1

The guides do instruct Jane to remove repos other than Kabanero if they are working with curated collections. We can try and ensure that this message is included in all the Docs/Guides to reinforce this message. 

Maybe here too:  https://kabanero.io/docs/ref/general/kabanero-cr-config.html (the part where the collection repo is described. We could explicitly state that it should contain the URL for the enterprise collection hub). Let me know if this helps and I'll get something in for Friday 0.3.0.

**Comment by SueChaplain** [comment]
@kvijai82 - I added you to a review on https://github.com/kabanero-io/guide-collection-springboot2/pull/7 to reinforce message for developers. 

I also requested the same update in the MicroProfile guide https://github.com/kabanero-io/guide-collection-microprofile/issues/20

**Comment by kvijai82** [comment]
@SueChaplain added a minor comment to consider in the PR.  Otherwise looks ok to me.

**Comment by kvijai82** [comment]
PR is merged and updated published.  Closing issue.
