### ISSUE TITLE
Jane is able to update the location of stack image to pull for pipeline run

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-pipelines#115]
This is design issue where pipelines/collection should not be using the registry defined by Jane in .appsody-config.yaml file but using the registry defined by Champ in collections/kabanero-config.yaml file.

Since pipeline only look into dockerhub for stack images, I tried to update the .appsody-config.yaml file to have the internal registry prefixed:
```
project-name: test
stack: docker-registry.default.svc:5000/kabanero/<mystack>
```

Pipelines try to use this location specified by Jane although it ends  up in an certificate error.
```
Extracting project from development environment
Pulling docker image docker-registry.default.svc:5000/kabanero/<mystack>
Running command: buildah pull docker-registry.default.svc:5000/kabanero/<mystack>
Error initializing source docker://docker-registry.default.svc:5000/kabanero/<mystack>
:latest: pinging docker registry returned: Get https://docker-registry.default.svc:5000/v2/: x509: certificate signed by unknown authority[Warning] Docker image pull failed: exit status 1[Warning] Could not run docker image ls -q for the image: docker-registry.default.svc:5000/kabanero/<mystack>
```

**Comment by mtamboli** [comment]
@stephenkinder @dacleyra @kvijai82 FYI

**Comment by marikaj123** [comment]
Need further discussion with Appsody in case it is the desired behavior.

**Comment by neeraj-laad** [comment]
Appsody now allows overriding the registry value during run/test/debug/build/deploy by passing in `--stack-registry` flag. 

Perhaps the pipelines should just sue this flag to override the registry. If the image is not there, the pipeline will fail.

**Comment by mtamboli** [comment]
@neeraj-laad Thank you! 
@kvijai82 See if pipelines can use this now.

**Comment by marikaj123** [comment]
@kvijai82 and @tseelbach - Can you please provide a status update

**Comment by marikaj123** [comment]
Vijai will update the pipeline to pull the new Appsody container.

**Comment by aadeshpa** [comment]
The changes has been done and below is the pull request:
https://github.com/kabanero-io/kabanero-pipelines/pull/153

The changes has been tested for all the pipelines.

**Comment by aadeshpa** [comment]
The pull request created in the collections repository for this issue is : https://github.com/kabanero-io/collections/pull/232

**Comment by marikaj123** [comment]
Ready for SVT to verify and close

**Comment by marikaj123** [comment]
@mtamboli - Please close the issue after verification. Thank you.

**Comment by mtamboli** [comment]
Verified the defect on kabanero 0.5rc2 driver. 

Updated the .appsody-config.yaml with registry which is not active and pipeline validation fails as expected:

`The Kabanero collection contained in image-registry.openshift-image-registry.svc:5000/kabanerobeta/java-microprofile:0.2 is not active on this system and cannot be built`
