### ISSUE TITLE
Add collection validation step to all Kabanero build / dev pipelines

### ISSUE THREAD

**Issue by smcclem** [kabanero-io/kabanero-pipelines#12]
Any Kabanero pipeline that builds from appsody source project must first validate that the target Kabanero collection and version is used to compile and run against.  

The  .appsody-config.yaml points to a docker image that should be the docker image associated with the Kabanero collection originally used to create the appsody project (during appsody init).  However, .appsody-config.yaml can be altered by Jane during development for a variety of reasons.

When the development pipeline is kicked off, we must first verify that .appsody-config.yaml hasn't been altered by Jane.  If it has been, we will fail the pipeline with a corresponding error message.

**Comment by smcclem** [comment]
Blocked by https://github.com/kabanero-io/kabanero-operator/issues/159

**Comment by davco01a** [comment]
you can display the detailed metadata of the collection with the following command:

e.g.

kubectl get collection java-microprofile -o yaml
