### ISSUE TITLE
Pipeline release process

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-pipelines#127]
Create a release process for pipelines that will generate the pipeline artifacts that will be need to be activated by the operator in a tar.gz.

**Comment by marikaj123** [comment]
@garypicher - Is the work schedule to complete in 0.5.0 or 0.6.0?

**Comment by kvijai82** [comment]
We have a travis build now that zips up the appropriate artifacts and attaches it to the release.
