### ISSUE TITLE
Pipelines need to use specific version of appsody/appsody-buildah image

### ISSUE THREAD

**Issue by groeges** [kabanero-io/kabanero-pipelines#128]
The appsody/appsody-buildah docker image that the pipelines has been modified recently to potentially fix an issue with some buildah commands taking a long time to execute. The latest version is now 0.5.0 (
docker pull appsody/appsody-buildah:0.5.0)

The current pipelines only specify to use the latest version of the appsody/appsody-buildah image. 

It may be a good idea to fix the version that the pipelines use in order to stop any changes to the image potentially causing all the pipelines to fail - as the image is not tied to any Kabanero release and may be chnaged at any time.

**Comment by kvijai82** [comment]
Updated pipelines to use 0.2.1 for now with a plan to move to 0.5 in the 0.4.0 kabanero release.
