### ISSUE TITLE
Automated testing for pipelines

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-pipelines#131]
As part of normal agile development, we need to have a set of automated regression tests which validates critical pipeline features which can be used for regression and release candidate testing.

**Comment by marikaj123** [comment]
@smcclem - Can you please document automation and then close this issue.

**Comment by marikaj123** [comment]
According to Vijai, targeting fro v0.5.0.

**Comment by kvijai82** [comment]
Test script added here:  https://github.com/kabanero-io/kabanero-pipelines/blob/master/pipelines/tests/test_active_collections.sh . 

Also found that there are atleast 2 other teams with similar test cases.  Will work with them to consolidate into one set of tests.
