### ISSUE TITLE
Collection hub build pipeline prototype

### ISSUE THREAD

**Issue by stephenkinder** [kabanero-io/kabanero-pipelines#133]
We'd like to deliver an example collection hub build pipeline to simplifying collection lifecycle management.  Eventually, we'll teach kabanero to react to GitHub events to drive this pipeline.

**Comment by groeges** [comment]
The same issue that @stephenkinder raised on the Collections board was closed by him with this comment: https://github.com/kabanero-io/collections/issues/171#issuecomment-560597448
Should this issue also be closed until it is decided what needs to be done. I don't want time and effort to be wasted doing this is it is deemed not needed at the moment.

**Comment by kvijai82** [comment]
Not setting up collection hubs anymore.
