### ISSUE TITLE
Pipelines uses incorrect appsody repository information 

### ISSUE THREAD

**Issue by groeges** [kabanero-io/kabanero-pipelines#137]
![image](https://user-images.githubusercontent.com/23166924/69233970-e3e1bf80-0b85-11ea-8a00-fc68de7dd818.png)

The above image shows the Appsody repository stacks rather than the Kabanero collections.

I think this is an issue with the default/build-task.yaml pipeline. Within this yaml the pipeline does the following:
```
          echo "Checking for configmap value....DEFAULT_COLLECTION_IMAGE_REGISTRY_URL=$DEFAULT_COLLECTION_IMAGE_REGISTRY_URL"
          echo "appsody-yaml-file-path=$(inputs.params.appsody-yaml-file-path)"
          if [ -f "$(inputs.params.appsody-yaml-file-path)" ]
          then
              echo "Appsody yaml file $(inputs.params.appsody-yaml-file-path) exists."
          else
              echo "Appsody yaml file $(inputs.params.appsody-yaml-file-path) does not exists, we are creating it by running appsody list command."
              appsody list
          fi
```
which if the file doesn’t exist will run `appsody list`. 

The Appsody executable that is setup on the appsody-buildah image is  setup to have the Appsody  `experimental` and `incubator` repositories configured (which is what I would expect as this image is not a Kabenero image).

If we are going to be doing an `appsody list` to pickup the Kabanero colections then we need to modify the repository list to point to the Kabanero repository and remove the Appsody repositories in order to get the correct collections listed.

**Comment by jgawor** [comment]
The `appsody list` seems like a huge overkill to just create the appsody configuration file. And that makes a remote call. None of that seems necessary.

**Comment by mtamboli** [comment]
@marikaj123, FYI

**Comment by marikaj123** [comment]
@jarek and @kvijai82 - is this a stopship issue for Kabanero release 0.3.0?

**Comment by mtamboli** [comment]
From my perspective, it is almost stop ship not because function is broken but it is confusing and alarming to see all those stacks show up in pipeline for Champ. So if there is any chance of 0.3.1 release, it should go in.

**Comment by marikaj123** [comment]
Monica is testing the collection 0.3.2 and then will close it.

**Comment by mtamboli** [comment]
I do not see `appsody list` anymore when using kabanero 0.3.2 collections so problem seems to be resolved.
