### ISSUE TITLE
Travis build for the kabanero-pipelines repo

### ISSUE THREAD

**Issue by smcclem** [kabanero-io/kabanero-pipelines#14]
We need to hook into the https://travis-ci.org/kabanero-io/ build framework.  I think we have some prereq on on the kabanero-operator laying the groundwork.  We would need a test system that the operator has already been run on prior to running our pipelines. 

This is the closest issue the kabanero-operator/ repo has right now:  https://github.com/kabanero-io/kabanero-operator/issues/6

**Comment by StringCheeseCR** [comment]
Hi @smcclem I'm looking into the "test" framework for Kabanero as a whole. Kyle mentioned the need to use tekton pipelines for this and the need to have a system available already to kick the whole process. I'm working on details of where we can get the infrastructure available to do builds and testing as well.

**Comment by StringCheeseCR** [comment]
https://github.com/kabanero-io/roadmap/issues/57

**Comment by tseelbach** [comment]
Need to make progress in 19.19.  May want to narrow this down to just getting a Travis build working.   Test would be ideal but that could be split into another issue.

**Comment by kvijai82** [comment]
Have a travis build now for the release process.  Will open more specific issues as we look to enhance this going forward.
