### ISSUE TITLE
The image-scan task is not collection-specific

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-pipelines#141]
It seems like the image-scan-task should contain the following, like the other tasks:
```
#Kabanero! on activate substitute CollectionId for text 'CollectionId'
```
and then pre-pend the task name with `CollectionId-`.

Otherwise, all of the collections are going to use the same Task, and if any collection deactivates, the image-scan task will get deleted.
https://github.com/kabanero-io/kabanero-pipelines/blob/master/pipelines/incubator/image-scan-task.yaml

**Comment by kvijai82** [comment]
Fixed it to use collection specific names
