### ISSUE TITLE
Update pipelines to work with next release of Tekton with Triggers

### ISSUE THREAD

**Issue by anneqm** [kabanero-io/kabanero-pipelines#145]
Update all pipelines to include one TriggerTemplate and two TriggerBindings per pipeline. TriggerBindings are for github-push and github-pull-request events. 
Refer to sample here: https://github.com/pipeline-hotel/example-pipelines  (see triggers-resources folder)

**Comment by brianxjx** [comment]
https://github.com/tektoncd/experimental/issues/400

**Comment by ncskier** [comment]
If I understand this issue correctly, I don't think that https://github.com/tektoncd/experimental/issues/400 is a blocker. https://github.com/tektoncd/experimental/issues/400 is not a bug; right now kabanero pipelines can be created, installed, and run properly on v0.3.0 of the Dashboard & Webhooks Extension.

https://github.com/tektoncd/experimental/issues/400 is just a change that would make the user experience a little nicer. However, it would require a pretty large architectural change to the Webhooks Extension. So, it's not a quick fix.

**Comment by mnuttall** [comment]
As a workaround please install each Pipeline and its associated Triggers resources into two namespaces:
- `kabanero` or wherever the webhooks-extension is running, and 
- the target namespace in which the pipeline is expected to execute. 

It is not currently worth making the requested change in the webhooks extension.

**Comment by kaczyns** [comment]
@muttall I just wanted to get clarification on your previous comment:
* We do not modify the tekton dashboard or webhook extension install yaml, so the webhooks-extension is installed in the `tekton-pipelines` namespace, not the `kabanero` namespace.  Please confirm that the `tekton-pipelines` namespace is one of the two namespaces we should be installing the pipelines and triggers into.
* When you say "it is not currently worth making the requested change in the webhooks extension", are you intending this workaround to be a permanent workaround?  It's not clear what you mean by "currently", whether this is a change you intend to make for a future version of the dashboard, or whether this is not a change on your radar at all.

**Comment by kaczyns** [comment]
@ncskier I appreciate what you are saying here, but there are some architectural challenges that this causes which didn't exist before, namely:
1) The service account creating the pipelines might not have access to the `tekton-pipelines` namespace.  Sure, we can give it access to the `tekton-pipelines` namespace, because we own it, but that may not always be the case.
2) I now have a limitation that my pipeline names need to be unique in the cluster.  This may be hard to enforce in practice.  I don't think that this limitation existed before.

**Comment by mnuttall** [comment]
@kaczyns I thought you hacked our namespace to `kabanero` but if you don't then yes, the dashboard and webhooks extension install to the `Tekton-pipelines` namespace by default. 

https://github.com/tektoncd/experimental/blob/master/webhooks-extension/docs/Limitations.md lays out where things need to go: basically everything goes into the `Tekton-pipelines` namespace except for the target `Pipeline` which needs to be in the namespace in which the PipelineRun will execute. If dual-copying all Tekton resources into both namespaces is not acceptable, then please don't do that, and stick to the documented restrictions as-is.

Kabanero has approximately one pipeline, so splitting it and its trigger resources between two namespaces should not be terribly onerous. Our understanding is that Kabanero wishes to move to an alternative method of managing webhooks, pipelines and triggers. Our recommendation is that the 'split namespace problem' is first tackled within the context of that alternative.

**Comment by anneqm** [comment]
@brianxjx @tseelbach is this one still blocked by Tekton?

**Comment by stephenkinder** [comment]
@anneqm We've decided that we will live with the limitation of the Tekton trigger documents for the 0.5.0 release.  We are considering alternative webhook technology and look to address the namespace and multi-tenancy work as we go forward throughout the year.
