### ISSUE TITLE
Create a validation task instead of step

### ISSUE THREAD

**Issue by kvijai82** [kabanero-io/kabanero-pipelines#150]
We are redoing this work in a few pipelines now.  Should be a task instead of step to avoid duplication.

**Comment by aadeshpa** [comment]
Pull request created: testing the changes before we merge this in the master
https://github.com/kabanero-io/kabanero-pipelines/pull/170

**Comment by aadeshpa** [comment]
The pull request with the changes are ready to be merged.

**Comment by kvijai82** [comment]
Merged and updated all pipelines to use the new task.
