### ISSUE TITLE
nodejs-loopback-build-push-deploy-pipeline-run result status is inconsistent

### ISSUE THREAD

**Issue by tam512** [kabanero-io/kabanero-pipelines#155]
- Test Kabanero 0.5.0-rc2, run `nodejs-loopback-build-push-deploy-pipeline`, the PipelineRuns Status shows as failed with message `PipelineRun "nodejs-loopback-build-push-deploy-pipeline-run-s55ts" failed to finish within "&Duration{Duration:1h0m0s,}"`(known defects https://github.com/kabanero-io/kabanero-pipelines/issues/121, https://github.ibm.com/IBMCloudPak4Apps/icpa-system-test/issues/115), but when viewing inside the nodejs-loopback-build-push-deploy-pipeline-run, all steps under `build-push-deploy-task` and `image-scan-task` show as green/passed.  If the pipelinerun is failed, the step inside the pipeline run should show as failed also

![Screen Shot 2020-01-15 at 1 08 00 PM](https://user-images.githubusercontent.com/22480038/72463096-15e35c80-3798-11ea-9b18-f5abf220d7ae.png)

![Screen Shot 2020-01-15 at 1 06 58 PM](https://user-images.githubusercontent.com/22480038/72462963-ecc2cc00-3797-11ea-981d-23a1fd3458d0.png)

- Tekton version is v0.8.0
```
# oc get kabanero -n kabanero -o yaml
apiVersion: v1
items:
- apiVersion: kabanero.io/v1alpha1
  kind: Kabanero
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"kabanero.io/v1alpha1","kind":"Kabanero","metadata":{"annotations":{},"name":"kabanero","namespace":"kabanero"},"spec":{"collections":{"repositories":[{"activateDefaultCollections":true,"name":"central","url":"https://github.com/kabanero-io/collections/releases/download/0.5.0-rc.3/kabanero-index.yaml"}]},"version":"0.5.0"}}
    creationTimestamp: "2020-01-14T22:56:07Z"
    finalizers:
    - kabanero.io.kabanero-operator
    generation: 3
    name: kabanero
    namespace: kabanero
    resourceVersion: "93188"
    selfLink: /apis/kabanero.io/v1alpha1/namespaces/kabanero/kabaneros/kabanero
    uid: 0c8b422a-3721-11ea-b529-00000a1a02d4
  spec:
    admissionControllerWebhook: {}
    che:
      cheOperatorInstance: {}
      enable: false
      kabaneroChe: {}
    cliServices: {}
    collectionController: {}
    collections:
      repositories:
      - activateDefaultCollections: true
        name: central
        url: https://github.com/kabanero-io/collections/releases/download/0.5.0-rc.3/kabanero-index.yaml
    events: {}
    github: {}
    landing: {}
    targetNamespaces:
    - svt-project1
    - svt-project2
    - svt-project3
    tekton: {}
    version: 0.5.0
  status:
    admissionControllerWebhook:
      ready: "True"
    appsody:
      ready: "True"
      version: 0.3.0
    cli:
      hostnames:
      - kabanero-cli-kabanero.apps.toast.os.fyre.ibm.com
      ready: "True"
    collectionController:
      ready: "True"
      version: 0.5.0-rc.1
    kabaneroInstance:
      ready: "True"
      version: 0.5.0
    knativeEventing:
      ready: "True"
      version: 0.9.0
    landing:
      ready: "True"
      version: 0.5.0-rc.1
    serverless:
      knativeServing:
        ready: "True"
        version: 0.9.0
      ready: "True"
      version: 1.2.0
    tekton:
      ready: "True"
      version: v0.8.0
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
- My Tekton dashboard version is v0.3.0
```
# kubectl get pod tekton-dashboard-5646944d99-bdfw2 -n tekton-pipelines -o yaml | grep image
    image: openshift/oauth-proxy@sha256:6bc1759a3202b4614739f12441461e344907f6b3f758c34314284debe36d4e15
    imagePullPolicy: IfNotPresent
    image: gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard@sha256:7ccc937d9dbd3a4e769ed81ab8256e369488813554700889d74855f811f161b0
    imagePullPolicy: IfNotPresent
  imagePullSecrets:
    image: docker.io/openshift/oauth-proxy@sha256:6bc1759a3202b4614739f12441461e344907f6b3f758c34314284debe36d4e15
    imageID: docker.io/openshift/oauth-proxy@sha256:6bc1759a3202b4614739f12441461e344907f6b3f758c34314284debe36d4e15
    image: gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard@sha256:7ccc937d9dbd3a4e769ed81ab8256e369488813554700889d74855f811f161b0
    imageID: gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard@sha256:7ccc937d9dbd3a4e769ed81ab8256e369488813554700889d74855f811f161b0
```
- Go to URL https://console.cloud.google.com/gcr/images/tekton-releases/GLOBAL/github.com/tektoncd/dashboard/cmd/dashboard@sha256:7ccc937d9dbd3a4e769ed81ab8256e369488813554700889d74855f811f161b0/details?tab=info and the tag shows v0.3.0
```
Container classification
Digest	
sha256:7ccc937d9dbd3a4e769ed81ab8256e369488813554700889d74855f811f161b0 
Tags	
v0.3.0
Repository	
github.com/tektoncd/dashboard/cmd/dashboard
Project	
tekton-releases
```

**Comment by marikaj123** [comment]
@aadeshpa - Ashis is testing this issue to determine if it is a Kabanero or Tekton issue.

**Comment by aadeshpa** [comment]
I verified with below configuration of Kabanero in my fyre cluster

```
    collections:
      repositories:
      - activateDefaultCollections: true
        name: central
        url: https://github.com/kabanero-io/collections/releases/download/0.4.0/kabanero-index.yaml
    github: {}
    landing: {}
    tekton: {}
    version: 0.4.0
    webhook: {}
  status:
    admissionControllerWebhook:
      ready: "True"
    appsody:
      ready: "True"
      version: 0.2.2
    cli:
      hostnames:
      - kabanero-cli-kabanero.apps.vespers.os.fyre.ibm.com
      ready: "True"
    collectionController:
      ready: "True"
      version: 0.4.0
    kabaneroInstance:
      ready: "True"
      version: 0.4.0
    knativeEventing:
      ready: "True"
      version: 0.9.0
    landing:
      ready: "True"
      version: 0.4.0
    serverless:
      knativeServing:
        ready: "True"
        version: 0.8.1
      ready: "True"
      version: 1.1.0
    tekton:
      ready: "True"
      version: v0.7.0
```

I see after the timeout of 60 min the pipeline shows as failed and the the `build` step shown to be loading with other two steps not run at all

Screenshot 1

<img width="1411" alt="Screen Shot 2020-01-16 at 11 02 06 AM" src="https://user-images.githubusercontent.com/53223993/72540983-ba74a580-384f-11ea-8e6d-0e6a9865d546.png">

Screenshot 2

<img width="1420" alt="Screen Shot 2020-01-16 at 11 02 19 AM" src="https://user-images.githubusercontent.com/53223993/72541006-c496a400-384f-11ea-8536-4219f1e6b858.png">

**Comment by aadeshpa** [comment]
Adding the comment from issue #86 

 ncskier commented 4 hours ago •
@tam512 I just verified that I also see the bug when running Tekton Dashboard v0.3.0 and Tekton Pipelines v0.8.0.  This bug was fixed in the Tekton Dashboard v0.2.1 with PR tektoncd/dashboard#653. However, the fix PR was reverted for Dashboard v0.3.0 when Tekton Pipelines v0.9.0 fixed an underlying issue causing the bug tektoncd/dashboard#795. Unfortunately, Dashboard v0.3.0 is now bundled with Tekton Pipelines v0.8.0. So, we have the bug again. I just verified that once the version of Tekton Pipelines is bumped up to v0.9.0 or greater, this bug will be resolved:  UPDATE: I was assuming that the next Kabanero release would bump up  the Tekton Pipelines version to v0.9.0 or greater. However, apparently  that's not the case. So it might be worthwhile to revert tektoncd/dashboard#795 to patch up the Dashboard to work with Tekton Pipelines v0.8.0.
--

**Comment by aadeshpa** [comment]
This issue is similar to issue #86 and hence we would need tekton to get the issue fix back in 0.9.0 version so we could verify it later. Marking it as blocked by Tekton for now.

**Comment by marikaj123** [comment]
According to Vijai, This is more of a user experience than a functional one.  It's purely a Tekton Issue.  Kabanero has no workaround for this issue.
@anneqm - Please inform us of a recommended Tekton version that we can include in Kabanero v0.6.0.

**Comment by a-roberts** [comment]
> Adding the comment from issue #86
> 
> ncskier(Brandon Walker) commented 4 hours ago •
> @tam512 I just verified that I also see the bug when running Tekton Dashboard v0.3.0 and Tekton Pipelines v0.8.0. This bug was fixed in the Tekton Dashboard v0.2.1 with PR [tektoncd/dashboard#653](https://github.com/tektoncd/dashboard/pull/653). However, the fix PR was reverted for Dashboard v0.3.0 when Tekton Pipelines v0.9.0 fixed an underlying issue causing the bug [tektoncd/dashboard#795](https://github.com/tektoncd/dashboard/pull/795). Unfortunately, Dashboard v0.3.0 is now bundled with Tekton Pipelines v0.8.0. So, we have the bug again. I just verified that once the version of Tekton Pipelines is bumped up to v0.9.0 or greater, this bug will be resolved: UPDATE: I was assuming that the next Kabanero release would bump up the Tekton Pipelines version to v0.9.0 or greater. However, apparently that's not the case. So it might be worthwhile to revert [tektoncd/dashboard#795](https://github.com/tektoncd/dashboard/pull/795) to patch up the Dashboard to work with Tekton Pipelines v0.8.0.

Can you try with 0.4.1 of our dashboard and extension please? I've let @kaczyns know too

**Comment by anneqm** [comment]
@marikaj123 @aadeshpa Please see Adam's comment above. Thanks, @a-roberts

**Comment by marikaj123** [comment]
According to Adam: So for 155 (and anything else to do with the displaying of TaskRuns), against Tekton 0.8 you should pick up 0.4.1 of our dashboard and extension yeah and see if you hit the same problem, we certainly had master specific (e.g. Tekton 0.9) specific code in the dashboard that we had to take out for the 0.4.1 release to support Tekton 0.8

**Comment by marikaj123** [comment]
Svt team is testing this as part of release 0.5.0.

**Comment by marikaj123** [comment]
@kaczyns - need 0.5.0rc release to include 0.4.1 of Tekton dashboard and extension.

**Comment by marikaj123** [comment]
@tam512 - Please verify the issue based on the new operator version 0.5.0-RC3.

**Comment by tam512** [comment]
Verified with Kabanero 0.5.0-rc.3, and I can see the consistent failure status when running loopback pipeline

<img width="1010" alt="Screen Shot 2020-01-24 at 10 12 04 PM" src="https://user-images.githubusercontent.com/22480038/73116108-a20f2580-3ef6-11ea-953d-69b017f960d3.png">

and it keeps looping at build step 

<img width="1064" alt="Screen Shot 2020-01-24 at 10 14 40 PM" src="https://user-images.githubusercontent.com/22480038/73116131-f1edec80-3ef6-11ea-9478-514c5a99046e.png">
