### ISSUE TITLE
Shorten names of pipelines & tasks

### ISSUE THREAD

**Issue by kvijai82** [kabanero-io/kabanero-pipelines#158]
Folks are running into issues with the pipelineruns going beyond the 63 character k8s limit

**Comment by mtamboli** [comment]
This is causing issues with pipeline runs using webhook in kabanero-0.5rcv2 driver. Did not get into these problems in earlier driver.
`Missing or invalid Task kabanero/java-microprofile-build-push-deploy-task: Pod "java-microprofile-build-push-deploy-pipeline-run-4lx6r-r--ft5j6-pod-193417" is invalid: spec.volumes[3].name: Invalid value: "java-microprofile-build-push-deploy-pipeline-run-4lx6r-r-mw9vg-pvc": must be no more than 63 characters`

**Comment by mtamboli** [comment]
@marikaj123 @kvijai82 I am assuming this is going to make kabanero 0.5 release as well?

**Comment by kvijai82** [comment]
@mtamboli yes this needs to make it into 0.5.0.  Identified the root cause as an update we made as part of our move to tekton triggers.  So we have to fix it.  I made the changes and have a PR but my cluster died before I could test.  So I have to rebuild from scratch again.  Going to take a it longer than I hoped.

**Comment by marikaj123** [comment]
Work is in progress more info by tomorrow morning.

**Comment by kvijai82** [comment]
Testing blocked by https://github.com/kabanero-io/kabanero-pipelines/issues/164

**Comment by marikaj123** [comment]
PR is created and ready to be merged.

**Comment by kvijai82** [comment]
Changes are pushed out to collections.

**Comment by marikaj123** [comment]
@kvijai82 - Who can verify the fix and close the issue?

**Comment by mtamboli** [comment]
This is verified using 0.5 rc4 collections. So we can close this.
