### ISSUE TITLE
Update tasks / pipelines to use events provided by tekton triggers

### ISSUE THREAD

**Issue by kvijai82** [kabanero-io/kabanero-pipelines#159]
Modify build/push/deploy pipeline to use the deploy task.
Add a `Condition` for the `deploy` task.

**Comment by brianxjx** [comment]
Opened issue against Tekton
https://github.com/tektoncd/experimental/issues/451

I'm trying to make deployment task conditional on the merge&close git event. I chose my criteria from
https://developer.github.com/enterprise/2.17/v3/activity/events/types/#pullrequestevent
To that end i coded a condition using some additional params. Specifically pulling additional fields from the pull_request event.

**Comment by brianxjx** [comment]
Future possibilities exist.

Triggers v0.2.1 has a nice new feature where you can filter events based on a CEL expression (documentation here: https://github.com/tektoncd/triggers/blob/master/docs/eventlisteners.md#cel-interceptors). It sounds like you want something like the following in your EventListener:
interceptors:
  - cel:
      filter: "body.action.matches('closed') && body.merged.matches('true')"

**Comment by marikaj123** [comment]
@anneqm - Any idea when a fix would be available for tektoncd/experimental#451?

**Comment by brianxjx** [comment]
#451 is being rejected.  I don't know of a containable plan B for this issue.

**Comment by anneqm** [comment]
Tekton is working as designed... we need to open this as a new feature request, and the Tekton team will address, but not in time for this week's release.

**Comment by marikaj123** [comment]
@anneqm - Thank you for the info.  Can you please provide us with the link to the Tekton feature after it gets opened.

**Comment by anneqm** [comment]
@marikaj123 yes, will do. Tekton team is looking at options for a solution now.

**Comment by anneqm** [comment]
@marikaj123 @brianxjx Please see solution Aki proposes in last comment in the tektoncd/experimental repo: https://github.com/tektoncd/experimental/issues/451#issuecomment-583040521. Let us know if this helps.

**Comment by brianxjx** [comment]
https://github.com/kabanero-io/kabanero-pipelines/pull/207
