### ISSUE TITLE
Create and validate a build pipeline for the springboot collection

### ISSUE THREAD

**Issue by kvijai82** [kabanero-io/kabanero-pipelines#16]

**Comment by kvijai82** [comment]
Running into maven files not found issues when running appsody build in the pipeline.  Still investigating.

**Comment by kvijai82** [comment]
Was able to build the appsody project locally but when I push the changes to a repo and try to drive the build pipeline, it fails with this error:

error building image: error building stage: lstat /workspace/extracted/.mvn-stack-settings.xml: no such file or directory

Bit confused as to why this is happening with just the spring pipeline.  All the other collections worked.

**Comment by kvijai82** [comment]
Pipeline logs:


[root@kalathur-okd-dal-master tekton-example]# kubectl logs appsody-manual-pipeline-run-appsody-build-bqxs2-pod-a7ff5f --all-containers
{"level":"warn","ts":1565721909.0517523,"logger":"fallback-logger","caller":"logging/config.go:65","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
{"level":"info","ts":1565721909.0527756,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}
{"level":"warn","ts":1565721910.9134421,"logger":"fallback-logger","caller":"logging/config.go:65","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
{"level":"info","ts":1565721911.582322,"logger":"fallback-logger","caller":"git/git.go:102","msg":"Successfully cloned https://github.com/kvijai82/appsody-java-spring-boot2 @ master in path /workspace/git-source"}
"/var/run/docker.sock"
"/builder/tools"
"/workspace"
Source mount is "/var/lib/origin/openshift.local.volumes/pods/77a2e033-bdfa-11e9-b3a9-005056a2a700/volumes/kubernetes.io~empty-dir/workspace"
APPSODY_MOUNT_PROJECT=/var/lib/origin/openshift.local.volumes/pods/77a2e033-bdfa-11e9-b3a9-005056a2a700/volumes/kubernetes.io~empty-dir/workspace/git-source
total 12
-rw-r--r--. 1 root root   36 Aug 13 18:45 .appsody-config.yaml
-rw-r--r--. 1 root root  349 Aug 13 18:45 appsody-service.yaml
-rw-r--r--. 1 root root 1176 Aug 13 18:45 pom.xml
drwxr-xr-x. 4 root root  100 Aug 13 18:45 .
drwxr-xr-x. 4 root root   30 Aug 13 18:45 src
drwxr-xr-x. 8 root root  177 Aug 13 18:45 .git
drwxrwxrwx. 4 root root   41 Aug 13 18:45 ..
[Debug] Creating log dir /builder/home/.appsody/logs
[Debug] Logging to file /builder/home/.appsody/logs/appsody2019-08-13T18-45-13.087151025.log
[Debug] Running with command line args: appsody extract -v
[Debug] Creating /builder/home/.appsody/repository
[Debug] Creating /builder/home/.appsody/repository/repository.yaml
[Debug] Creating /builder/home/.appsody/.appsody.yaml
[Debug] Writing config file /builder/home/.appsody/.appsody.yaml
[Info] Extracting project from development environment
[Debug] Project config file set to: /workspace/git-source/.appsody-config.yaml
[Debug] Project stack from config file: appsody/java-spring-boot2:0.3
[Debug] Creating extract dir: /builder/home/.appsody/extract
[Debug] appsody/java-spring-boot2:0.3 image pulled status: false
[Debug] Pull policy Always
[Debug] Pulling docker image appsody/java-spring-boot2:0.3
[Info] Running command: docker[pull appsody/java-spring-boot2:0.3]
[Debug] Trying to pull repository docker.io/appsody/java-spring-boot2 ... 
[Debug] 0.3: Pulling from docker.io/appsody/java-spring-boot2
[Debug] Digest: sha256:73b7b239dd81495265beddc94ba3fae1dd989551481fd8fca3862f72a5df2f25
[Debug] Status: Image is up to date for docker.io/appsody/java-spring-boot2:0.3
[Debug] docker.io/appsody/java-spring-boot2:0.3
[Debug] Container project dir: /project
[Debug] appsody/java-spring-boot2:0.3 image pulled status: true
[Debug] Image has been pulled already: appsody/java-spring-boot2:0.3
[Debug] Number of environment variables in stack image: 22
[Debug] All environment variables in stack image: [PATH=/opt/ibm/java/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin JAVA_VERSION=1.8.0_sr5fp36 JAVA_HOME=/opt/ibm/java/jre IBM_JAVA_OPTIONS=-XX:+UseContainerSupport MAVEN_HOME=/usr/share/maven MAVEN_CONFIG=/root/.m2 APPSODY_USER_RUN_AS_LOCAL=true APPSODY_MOUNTS=.:/project/user-app;~/.m2/repository:/mvn/repository APPSODY_DEPS= APPSODY_WATCH_DIR=/project/user-app/src APPSODY_WATCH_IGNORE_DIR= APPSODY_WATCH_REGEX= APPSODY_RUN=/project/java-spring-boot2-build.sh run APPSODY_RUN_ON_CHANGE=/project/java-spring-boot2-build.sh recompile APPSODY_RUN_KILL=false APPSODY_DEBUG=/project/java-spring-boot2-build.sh debug APPSODY_DEBUG_ON_CHANGE= APPSODY_DEBUG_KILL=false APPSODY_TEST=/project/java-spring-boot2-build.sh test APPSODY_TEST_ON_CHANGE= APPSODY_TEST_KILL=true PORT=8080]
[Debug] Environment variable found: APPSODY_MOUNTS Value: .:/project/user-app;~/.m2/repository:/mvn/repository
[Debug] Overriding project mount dir from '/workspace/git-source' to APPSODY_MOUNT_PROJECT value '/var/lib/origin/openshift.local.volumes/pods/77a2e033-bdfa-11e9-b3a9-005056a2a700/volumes/kubernetes.io~empty-dir/workspace/git-source' 
[Debug] Checking for existence of local file or directory to mount: /builder/home/.m2/repository
[Info] Running command: docker[create --name git-source-extract -v /var/lib/origin/openshift.local.volumes/pods/77a2e033-bdfa-11e9-b3a9-005056a2a700/volumes/kubernetes.io~empty-dir/workspace/git-source/.:/project/user-app appsody/java-spring-boot2:0.3]
[Warning] Could not mount /builder/home/.m2/repository:/mvn/repository because the local file was not found.
[Debug] Mapped mount args: [-v /var/lib/origin/openshift.local.volumes/pods/77a2e033-bdfa-11e9-b3a9-005056a2a700/volumes/kubernetes.io~empty-dir/workspace/git-source/.:/project/user-app]
[Debug] 1b4e14b0e77ffe0f119ab9b59d37142ce9f0b7713efcde40b95223b70e58f84a
[Info] Running command: docker[cp git-source-extract:/project /builder/home/.appsody/extract/git-source]
[Info] Running command: docker[rm git-source-extract -f]
[Debug] git-source-extract
[Info] Project extracted to /builder/home/.appsody/extract/git-source
total 20
drwxrwxrwx. 4 root root   41 Aug 13 18:45 ..
-rw-r--r--. 1 root root   21 Aug 13 18:45 stack.properties
-rwxr-xr-x. 1 root root 3703 Aug 13 18:45 java-spring-boot2-build.sh
-rw-r--r--. 1 root root 5866 Aug 13 18:45 appsody-boot2-pom.xml
-rw-r--r--. 1 root root 1382 Aug 13 18:45 Dockerfile
drwxr-xr-x. 3 root root  127 Aug 13 18:45 .
drwxr-xr-x. 4 root root  100 Aug 13 18:45 user-app
[]
INFO[0000] Resolved base name maven:3.6-ibmjava-8 to maven:3.6-ibmjava-8 
INFO[0000] Resolved base name adoptopenjdk:8-jdk-openj9 to adoptopenjdk:8-jdk-openj9 
INFO[0000] Resolved base name maven:3.6-ibmjava-8 to maven:3.6-ibmjava-8 
INFO[0000] Resolved base name adoptopenjdk:8-jdk-openj9 to adoptopenjdk:8-jdk-openj9 
INFO[0000] Downloading base image maven:3.6-ibmjava-8   
INFO[0000] Error while retrieving image from cache: getting file info: stat /cache/sha256:095701f537a542c25e3eb5894cc972577eb99d24efaebacf84f9b007531292f0: no such file or directory 
INFO[0000] Downloading base image maven:3.6-ibmjava-8   
INFO[0000] Downloading base image adoptopenjdk:8-jdk-openj9 
INFO[0001] Error while retrieving image from cache: getting file info: stat /cache/sha256:2c53b853578956ac8ef18f965a53f48fc2cd6090730ac337922bce80726bf55b: no such file or directory 
INFO[0001] Downloading base image adoptopenjdk:8-jdk-openj9 
INFO[0001] Built cross stage deps: map[0:[/project/user-app/target/app.jar]] 
INFO[0001] Downloading base image maven:3.6-ibmjava-8   
INFO[0001] Error while retrieving image from cache: getting file info: stat /cache/sha256:095701f537a542c25e3eb5894cc972577eb99d24efaebacf84f9b007531292f0: no such file or directory 
INFO[0001] Downloading base image maven:3.6-ibmjava-8   
INFO[0001] Unpacking rootfs as cmd RUN  apt-get -qq update   && apt-get -qq install -y curl wget xmlstarlet unzip   && DEBIAN_FRONTEND=noninteractive apt-get -qq upgrade -y   && apt-get -qq clean   && rm -rf /tmp/* /var/lib/apt/lists/*   && mkdir -p /mvn/repository requires it. 
INFO[0014] Taking snapshot of full filesystem...        
INFO[0018] LABEL maintainer="IBM Java Engineering at IBM Cloud" 
INFO[0018] Applying label maintainer=IBM Java Engineering at IBM Cloud 
INFO[0018] RUN  apt-get -qq update   && apt-get -qq install -y curl wget xmlstarlet unzip   && DEBIAN_FRONTEND=noninteractive apt-get -qq upgrade -y   && apt-get -qq clean   && rm -rf /tmp/* /var/lib/apt/lists/*   && mkdir -p /mvn/repository 
INFO[0018] cmd: /bin/sh                                 
INFO[0018] args: [-c apt-get -qq update   && apt-get -qq install -y curl wget xmlstarlet unzip   && DEBIAN_FRONTEND=noninteractive apt-get -qq upgrade -y   && apt-get -qq clean   && rm -rf /tmp/* /var/lib/apt/lists/*   && mkdir -p /mvn/repository] 
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package sgml-base.
(Reading database ... 5305 files and directories currently installed.)
Preparing to unpack .../sgml-base_1.26+nmu4ubuntu1_all.deb ...
Unpacking sgml-base (1.26+nmu4ubuntu1) ...
Selecting previously unselected package libicu55:amd64.
Preparing to unpack .../libicu55_55.1-7ubuntu0.4_amd64.deb ...
Unpacking libicu55:amd64 (55.1-7ubuntu0.4) ...
Selecting previously unselected package libxml2:amd64.
Preparing to unpack .../libxml2_2.9.3+dfsg1-1ubuntu0.6_amd64.deb ...
Unpacking libxml2:amd64 (2.9.3+dfsg1-1ubuntu0.6) ...
Selecting previously unselected package xml-core.
Preparing to unpack .../xml-core_0.13+nmu2_all.deb ...
Unpacking xml-core (0.13+nmu2) ...
Selecting previously unselected package libxslt1.1:amd64.
Preparing to unpack .../libxslt1.1_1.1.28-2.1ubuntu0.2_amd64.deb ...
Unpacking libxslt1.1:amd64 (1.1.28-2.1ubuntu0.2) ...
Selecting previously unselected package unzip.
Preparing to unpack .../unzip_6.0-20ubuntu1_amd64.deb ...
Unpacking unzip (6.0-20ubuntu1) ...
Selecting previously unselected package xmlstarlet.
Preparing to unpack .../xmlstarlet_1.6.1-1ubuntu1_amd64.deb ...
Unpacking xmlstarlet (1.6.1-1ubuntu1) ...
Processing triggers for libc-bin (2.23-0ubuntu11) ...
Setting up sgml-base (1.26+nmu4ubuntu1) ...
Setting up libicu55:amd64 (55.1-7ubuntu0.4) ...
Setting up libxml2:amd64 (2.9.3+dfsg1-1ubuntu0.6) ...
Setting up xml-core (0.13+nmu2) ...
Setting up libxslt1.1:amd64 (1.1.28-2.1ubuntu0.2) ...
Setting up unzip (6.0-20ubuntu1) ...
Setting up xmlstarlet (1.6.1-1ubuntu1) ...
Processing triggers for libc-bin (2.23-0ubuntu11) ...
Processing triggers for sgml-base (1.26+nmu4ubuntu1) ...
INFO[0027] Taking snapshot of full filesystem...        
INFO[0027] Adding whiteout for /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_InRelease 
INFO[0027] Adding whiteout for /var/lib/apt/lists/security.ubuntu.com_ubuntu_dists_xenial-security_universe_binary-amd64_Packages.lz4 
INFO[0027] Adding whiteout for /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-updates_multiverse_binary-amd64_Packages.lz4 
INFO[0027] Adding whiteout for /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_main_binary-amd64_Packages.lz4 
INFO[0027] Adding whiteout for /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-updates_universe_binary-amd64_Packages.lz4 
INFO[0027] Adding whiteout for /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-updates_restricted_binary-amd64_Packages.lz4 
INFO[0027] Adding whiteout for /var/lib/apt/lists/security.ubuntu.com_ubuntu_dists_xenial-security_multiverse_binary-amd64_Packages.lz4 
INFO[0027] Adding whiteout for /var/lib/apt/lists/lock  
INFO[0027] Adding whiteout for /tmp/cbe.a184546916c20011ba3 
INFO[0027] Adding whiteout for /tmp/cbe_a184546916c20011ba3.exit 
INFO[0027] Adding whiteout for /tmp/cbe_52e4445316c20012bb5.exit 
INFO[0027] Adding whiteout for /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_multiverse_binary-amd64_Packages.lz4 
INFO[0027] Adding whiteout for /tmp/cbe.cf8b7af016c20012de9 
INFO[0027] Adding whiteout for /tmp/cbe.52e4445316c20012bb5 
INFO[0027] Adding whiteout for /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease 
INFO[0027] Adding whiteout for /tmp/cbe_f1f45e3b16c2001302f.exit 
INFO[0027] Adding whiteout for /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_restricted_binary-amd64_Packages.lz4 
INFO[0027] Adding whiteout for /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_universe_binary-amd64_Packages.lz4 
INFO[0027] Adding whiteout for /tmp/cbe_cf8b7af016c20012de9.exit 
INFO[0027] Adding whiteout for /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-updates_main_binary-amd64_Packages.lz4 
INFO[0027] Adding whiteout for /var/lib/apt/lists/partial 
INFO[0027] Adding whiteout for /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-backports_universe_binary-amd64_Packages.lz4 
INFO[0027] Adding whiteout for /var/lib/apt/lists/security.ubuntu.com_ubuntu_dists_xenial-security_main_binary-amd64_Packages.lz4 
INFO[0027] Adding whiteout for /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-backports_main_binary-amd64_Packages.lz4 
INFO[0027] Adding whiteout for /var/lib/apt/lists/security.ubuntu.com_ubuntu_dists_xenial-security_InRelease 
INFO[0027] Adding whiteout for /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial-backports_InRelease 
INFO[0027] Adding whiteout for /var/lib/apt/lists/security.ubuntu.com_ubuntu_dists_xenial-security_restricted_binary-amd64_Packages.lz4 
INFO[0027] Adding whiteout for /tmp/cbe.f1f45e3b16c2001302f 
INFO[0030] Using files from context: [/workspace/extracted/stack.properties] 
INFO[0030] COPY ./stack.properties /project/stack.properties 
INFO[0030] Taking snapshot of files...                  
INFO[0030] RUN cd /usr/lib &&     KVER=$(cat /project/stack.properties | grep kotlin.version | sed 's/kotlin.version=//') &&     wget -q https://github.com/JetBrains/kotlin/releases/download/v$KVER/kotlin-compiler-$KVER.zip &&     unzip kotlin-compiler-*.zip &&     rm kotlin-compiler-*.zip &&     rm -f kotlinc/bin/*.bat 
INFO[0030] cmd: /bin/sh                                 
INFO[0030] args: [-c cd /usr/lib &&     KVER=$(cat /project/stack.properties | grep kotlin.version | sed 's/kotlin.version=//') &&     wget -q https://github.com/JetBrains/kotlin/releases/download/v$KVER/kotlin-compiler-$KVER.zip &&     unzip kotlin-compiler-*.zip &&     rm kotlin-compiler-*.zip &&     rm -f kotlinc/bin/*.bat] 
Archive:  kotlin-compiler-1.3.40.zip
   creating: kotlinc/
   creating: kotlinc/license/
  inflating: kotlinc/license/COPYRIGHT.txt  
  inflating: kotlinc/license/LICENSE.txt  
  inflating: kotlinc/license/README.md  
  inflating: kotlinc/license/NOTICE.txt  
   creating: kotlinc/license/third_party/
   creating: kotlinc/license/third_party/testdata/
  inflating: kotlinc/license/third_party/testdata/spring_license.txt  
  inflating: kotlinc/license/third_party/testdata/dagger_license.txt  
  inflating: kotlinc/license/third_party/testdata/lombok_license.txt  
  inflating: kotlinc/license/third_party/testdata/gradle_license.txt  
  inflating: kotlinc/license/third_party/testdata/findbugs_license.txt  
  inflating: kotlinc/license/third_party/testdata/eclipse_license.txt  
  inflating: kotlinc/license/third_party/testdata/rxjava_license.txt  
  inflating: kotlinc/license/third_party/testdata/eclipse_distribution_license.txt  
  inflating: kotlinc/license/third_party/qunit_license.txt  
  inflating: kotlinc/license/third_party/rhino_LICENSE.txt  
  inflating: kotlinc/license/third_party/prototype_license.txt  
  inflating: kotlinc/license/third_party/args4j_LICENSE.txt  
  inflating: kotlinc/license/third_party/trove_readme_license.txt  
  inflating: kotlinc/license/third_party/aosp_license.txt  
  inflating: kotlinc/license/third_party/gwt_license.txt  
  inflating: kotlinc/license/third_party/jquery_license.txt  
  inflating: kotlinc/license/third_party/pcollections_LICENSE.txt  
  inflating: kotlinc/license/third_party/dart_LICENSE.txt  
  inflating: kotlinc/license/third_party/trove_license.txt  
  inflating: kotlinc/license/third_party/asm_license.txt  
  inflating: kotlinc/license/third_party/closure-compiler_LICENSE.txt  
  inflating: kotlinc/license/third_party/guava_license.txt  
  inflating: kotlinc/license/third_party/boost_LICENSE.txt  
  inflating: kotlinc/license/third_party/jshashtable_license.txt  
  inflating: kotlinc/license/third_party/maven_LICENSE.txt  
  inflating: kotlinc/license/third_party/scala_license.txt  
  inflating: kotlinc/build.txt       
   creating: kotlinc/bin/
  inflating: kotlinc/bin/kotlinc-jvm.bat  
  inflating: kotlinc/bin/kotlinc     
  inflating: kotlinc/bin/kapt.bat    
  inflating: kotlinc/bin/kotlin.bat  
  inflating: kotlinc/bin/kotlinc.bat  
  inflating: kotlinc/bin/kotlinc-js  
  inflating: kotlinc/bin/kotlin-dce-js  
  inflating: kotlinc/bin/kotlin      
  inflating: kotlinc/bin/kapt        
  inflating: kotlinc/bin/kotlinc-js.bat  
  inflating: kotlinc/bin/kotlinc-jvm  
  inflating: kotlinc/bin/kotlin-dce-js.bat  
   creating: kotlinc/lib/
  inflating: kotlinc/lib/kotlin-scripting-compiler-impl.jar  
  inflating: kotlinc/lib/kotlin-stdlib-jdk7-sources.jar  
  inflating: kotlinc/lib/kotlin-runner.jar  
  inflating: kotlinc/lib/kotlin-test-junit5-sources.jar  
  inflating: kotlinc/lib/kotlinx-serialization-compiler-plugin.jar  
  inflating: kotlinc/lib/kotlin-script-runtime-sources.jar  
  inflating: kotlinc/lib/allopen-compiler-plugin.jar  
  inflating: kotlinc/lib/kotlin-preloader.jar  
  inflating: kotlinc/lib/jvm-abi-gen.jar  
  inflating: kotlinc/lib/kotlin-stdlib-jdk8.jar  
  inflating: kotlinc/lib/kotlin-compiler.jar  
  inflating: kotlinc/lib/kotlin-test.jar  
  inflating: kotlinc/lib/android-extensions-compiler.jar  
  inflating: kotlinc/lib/kotlin-annotation-processing.jar  
  inflating: kotlinc/lib/kotlin-daemon-client.jar  
  inflating: kotlinc/lib/kotlin-script-runtime.jar  
  inflating: kotlinc/lib/kotlin-stdlib-jdk8-sources.jar  
  inflating: kotlinc/lib/kotlin-main-kts.jar  
  inflating: kotlinc/lib/kotlin-reflect.jar  
  inflating: kotlinc/lib/mutability-annotations-compat.jar  
  inflating: kotlinc/lib/kotlin-annotations-jvm.jar  
  inflating: kotlinc/lib/kotlin-test-junit-sources.jar  
  inflating: kotlinc/lib/kotlin-test-testng.jar  
  inflating: kotlinc/lib/kotlin-test-testng-sources.jar  
  inflating: kotlinc/lib/kotlin-test-junit.jar  
  inflating: kotlinc/lib/kotlin-test-js-sources.jar  
  inflating: kotlinc/lib/kotlin-test-js.jar  
  inflating: kotlinc/lib/kotlin-reflect-sources.jar  
  inflating: kotlinc/lib/kotlin-annotation-processing-cli.jar  
  inflating: kotlinc/lib/kotlin-imports-dumper-compiler-plugin.jar  
  inflating: kotlinc/lib/trove4j.jar  
  inflating: kotlinc/lib/kotlin-stdlib-sources.jar  
  inflating: kotlinc/lib/kotlin-annotations-android.jar  
  inflating: kotlinc/lib/kotlin-test-junit5.jar  
  inflating: kotlinc/lib/sam-with-receiver-compiler-plugin.jar  
  inflating: kotlinc/lib/kotlin-ant.jar  
  inflating: kotlinc/lib/android-extensions-runtime.jar  
  inflating: kotlinc/lib/kotlin-annotation-processing-runtime.jar  
  inflating: kotlinc/lib/annotations-13.0.jar  
  inflating: kotlinc/lib/noarg-compiler-plugin.jar  
  inflating: kotlinc/lib/kotlin-scripting-jvm.jar  
  inflating: kotlinc/lib/kotlin-scripting-compiler.jar  
  inflating: kotlinc/lib/kotlin-stdlib-js-sources.jar  
  inflating: kotlinc/lib/kotlin-stdlib-js.jar  
  inflating: kotlinc/lib/kotlin-stdlib.jar  
  inflating: kotlinc/lib/kotlin-test-sources.jar  
  inflating: kotlinc/lib/kotlin-stdlib-jdk7.jar  
  inflating: kotlinc/lib/kotlin-annotations-jvm-sources.jar  
  inflating: kotlinc/lib/kotlin-scripting-common.jar  
  inflating: kotlinc/lib/kotlin-source-sections-compiler-plugin.jar  
INFO[0031] Taking snapshot of full filesystem...        
INFO[0034] Using files from context: [/workspace/extracted] 
INFO[0034] COPY . /project                              
INFO[0034] Taking snapshot of files...                  
**_error building image: error building stage: lstat /workspace/extracted/.mvn-stack-settings.xml: no such file or directory_**

**Comment by timroster** [comment]
observing identical behavior. I also have a non-trivial appsody project using the `stack: appsody/java-spring-boot2:0.3` that locally works with `appsody run`, builds with `appsody build` and also fails with the same error in the build pipeline.

**Comment by timroster** [comment]
It appears that the kaniko build of the container is failing at https://github.com/appsody/stacks/blob/cf540803f2a7b09527f8b7c53ceda293f6b65165/incubator/java-spring-boot2/image/project/Dockerfile#L23 because of the missing file. The file is missing because https://github.com/appsody/appsody-docker/blob/3ff31d134b1662653a964d87b3a5f4cd3ef36f31/setupAndRunExtract.sh#L44 will not match dot files from the source project directory and that's exactly what https://github.com/appsody/stacks/blob/cf540803f2a7b09527f8b7c53ceda293f6b65165/incubator/java-spring-boot2/image/Dockerfile-stack#L22 creates. 

Two possible fixes depending on intent for `setupAndRunExtract.sh` in appsody-docker. If dot files at the top level of the extracted directory are to be included, then the match needs to be updated. Other stacks at present seem not to require this functionality. 

In this case it seems preferable to not use a dot file for `mvn-stack-settings.xml` in the stack container for java-spring-boot2. @ebullient

**Comment by timroster** [comment]
created https://github.com/appsody/stacks/issues/196 as an issue to get this fixed. I don't think this is a kabanero problem at the current time.

**Comment by kvijai82** [comment]
Thanks @timroster for debugging this problem and opening the issue!

**Comment by timroster** [comment]
@kvijai82 should be fixed now by https://github.com/appsody/stacks/pull/210

**Comment by kvijai82** [comment]
@timroster thanks.  I tried to pick that up and got a bit further in the pipeline but build now failed with another error.  Opened https://github.com/appsody/stacks/issues/224 for that.  Did you have success getting the pipeline to complete the build?

**Comment by kvijai82** [comment]
@timroster worked for me now.  Ended up with a version mismatch earlier.  Think pipeline should be good now :)
