### ISSUE TITLE
Tekton pipeline build step fails for mixed case project names

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-pipelines#162]
This is a regression problem. Using the same project name which worked earlier fails now. Pipeline should be able to convert the image name to be all lower case as appsody CLI seems to be doing. 

Here are steps to recreate the issue.

1. Jane had Java microprofile project checked into GitHub with name `appsodyMPversion`. This project worked fine with kabanero 0.3 version.

2. Ran this project again with kabanero 0.5 and saw that the build step failed because project name is not all lowercase.
`Buildah] STEP 16: COMMIT image-registry.openshift-image-registry.svc:5000/kabanero/appsodyMPversion:a52c79d50aea14c7e0b33bcd6da437e34717344f[Buildah] error committing container for step {Env:[PATH=/opt/ol/wlp/bin:/opt/ol/docker/:/opt/ol/helpers/build:/opt/ibm/java/jre/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin container=oci JAVA_VERSION=1.8.0_sr5fp40 JAVA_HOME=/opt/ibm/java/jre IBM_JAVA_OPTIONS=-Xshareclasses:name=liberty,nonfatal,cacheDir=/output/.classCache/ -XX:+UseContainerSupport LOG_DIR=/logs WLP_OUTPUT_DIR=/opt/ol/wlp/output WLP_SKIP_MAXPERMSIZE=true RANDFILE=/tmp/.rnd] Command:expose Args:[9443] Flags:[] Attrs:map[] Message:EXPOSE 9443 Original:EXPOSE 9443}: error parsing target image name "image-registry.openshift-image-registry.svc:5000/kabanero/appsodyMPversion:a52c79d50aea14c7e0b33bcd6da437e34717344f": error parsing image name "image-registry.openshift-image-registry.svc:5000/kabanero/appsodyMPversion:a52c79d50aea14c7e0b33bcd6da437e34717344f": invalid reference format: repository name must be lowercase[Error] exit status 1`
![image](https://user-images.githubusercontent.com/29490950/72825826-bd9fd500-3c45-11ea-919f-44c8fba55ad0.png)

3. Jane can run `appsody build` and `appsody deploy` with mixed case project names. Although the generated image name is all lowercase. It is expected that pipleline should be able to work the same way.

**Comment by mtamboli** [comment]
I am marking this stop-ship and we need to discuss this to understand why this is failing.

**Comment by akihikokuroda** [comment]
This is an issue in the task.  I believe this should be looked at by the kabanero pipeline team.

**Comment by marikaj123** [comment]
Scott is working on the fix.

**Comment by mtamboli** [comment]
Successful build for project named `kabProShop`: 
```
STEP 10: COPY --chown=1001:0 --from=0 /config/ /opt/ol/wlp/usr/servers/defaultServer/
STEP 11: EXPOSE 9080
STEP 12: EXPOSE 9443
STEP 13: COMMIT image-registry.openshift-image-registry.svc:5000/kabanero/kabproshop:baab2fa
Getting image source signatures
Copying blob sha256:43c67172d1d182ca5460fc962f8f053f33028e0a3a1d423e05d91b532429e73d
Copying blob sha256:21ec61b65b20ec53a1b7f069fd04df5acb0e75434bd3603c88467c8bfc80d9c6
Copying blob sha256:1d0dfb259f6a31f95efcba61f0a3afa318448890610c7d9a64dc4e95f9add843
Copying blob sha256:f55aa0bd26b801374773c103bed4479865d0e37435b848cb39d164ccb2c3ba51
Copying blob sha256:e993ebdaa176d2f4c726067d33b836eeec5de7d492fb94cbe23bd44cd21a121e
Copying blob sha256:126bd571794646790b2a07a49e3b99c2857cd45ee26f8cac36bf2ccf0e067df1
Copying blob sha256:fc8a453a4864c051b9e99bb3ace8554e922e4cc223a50e364128ced2d27b6f20
Copying blob sha256:40821cc5ba1657cc114f9bea8f295b16e463b5675f44c1a33961e1e99f891ae4
Copying blob sha256:e6fec87fc30ee38122d71ec2c0f98e0f01a0354f0af2febdd1acd930936c6b60
Copying blob sha256:ad13b59ae8c8d56058de66ff352840cd63ecf635a3e477f22e5583d9fd9620ff
Copying blob sha256:102786f622efbdf9c3355f6cb43a541fb12536abe23812629024c12f9cfceeb9
Copying blob sha256:2fa15584a34cdaacdd0638e534456baf2e668207130dbc6e399af53feaf1ff61
Copying blob sha256:668649173c335fd3503334241ddc3ab8c6302b2415c0450bd5c7b8aedebf79d9
Copying blob sha256:35a9de1c1a6b86ac988a5e3ab1b7c8e94e644c160fe711621214be181564701b
Copying blob sha256:bd8ce8c00124cf1d98198d3ce9b5d64ac4e67256d4c0f4b135b39eec885b892b
Copying blob sha256:57c37fb0d1d918b113d45b976b9249a5d5e0ac4c9acc54a6c953b1b42c5165aa
Copying blob sha256:536247cf3a0b3a3e0584df2463130a72534578637cbbf2a1a3c2ec9c6c356045
Copying blob sha256:3a9ea2737e5bd278033fc6d0a52c54d4d12156e364d6f19f0678b0abbc0e3300
Copying blob sha256:4e9cb2f91a203faf1022d92746b4ab6a774919d6920f4b6126f5d253a1568e5b
Copying config sha256:0148ab118dc34453845b9df4020afd1a8d49f3c62c1ffd142fd5e573cc61d3b7
Writing manifest to image destination
Storing signatures
0148ab118dc34453845b9df4020afd1a8d49f3c62c1ffd142fd5e573cc61d3b7
Step completed
```

**Comment by mtamboli** [comment]
@kvijai82 @smcclem @aadeshpa @marikaj123 @stephenkinder 
Talked to @akihikokuroda on this issue. He investigated and found that this is happening due to the new design of Triggers. It would be nice if pipelines can convert this to lowercase as a short term solution and we see what make sense in long term from Tekton team.

**Comment by marikaj123** [comment]
PR is ready to merge.

**Comment by kvijai82** [comment]
Fix is pushed to collections in https://github.com/kabanero-io/collections/pull/256.  SVT, Please verify the issue is resolved in the latest collections RC.

**Comment by mtamboli** [comment]
I am able to verify that the mixed-use project names work with pipelines build-push pipeline now. Closing this defect. Thanks @smcclem  and @akihikokuroda for comping up with a way to fix this issue.
