### ISSUE TITLE
Syntax change for TriggerBindings for move up to Triggers 0.2.x (JSONPath instead of gjson syntax)

### ISSUE THREAD

**Issue by anneqm** [kabanero-io/kabanero-pipelines#165]
The move up to Tekton Triggers 0.2.x will require kababero-pipelines to update to use JSONPath query syntax instead of gjson syntax for the TriggerBindings.  For more details, please see https://github.com/tektoncd/triggers/releases/tag/v0.2.0

**Comment by kvijai82** [comment]
Based on the pipelines hotel example, it looks like the changes are happening at a layer below us.  Will test once I am able to pickup the new releases.

**Comment by kvijai82** [comment]
We had to update the trigger template to list out all the params we used in the spec section.  All the pipeline artifacts are now updated to work with the new tekton releases.
