### ISSUE TITLE
Create a guide on how to update existing pipelines for a stack

### ISSUE THREAD

**Issue by kvijai82** [kabanero-io/kabanero-pipelines#175]

**Comment by marikaj123** [comment]
@kvijai82 - Can you please assist in providing information to the ID team?

**Comment by marikaj123** [comment]
@jantley-ibm and @mingcyu - FYI: Vijai will provide you with the info as soon as he gets the tasks in the issue working.

**Comment by kvijai82** [comment]
Added doc here: https://github.com/kabanero-io/kabanero-pipelines/blob/doc-curate/docs/Curation.md and opened corresponding issue in the doc repo.
