### ISSUE TITLE
Improve troubleshooting guide

### ISSUE THREAD

**Issue by kvijai82** [kabanero-io/kabanero-pipelines#176]

**Comment by marikaj123** [comment]
@jantley-ibm and @mingcyu - FYI: Vijai will provide you with the info as soon as he gets the tasks in the issue working.

**Comment by marikaj123** [comment]
@kvijai82 - Was the work completed in 0.6.0 or do we need to move it to a newer release?

**Comment by kvijai82** [comment]
We did some work in 0.6.0 / 0.7.0.  But will be adding some more info in 0.8.0.

**Comment by mingcyu** [comment]
@kvijai82 Vijay, will there be updates to 0.9?

**Comment by kvijai82** [comment]
This was meant to be an ongoing thing to update the troubleshooting guide as we discovered new things.  Will open more specific issues going forward now that we have a base troubleshooting doc.
