### ISSUE TITLE
Identify a test framework to plug in pipelines tests

### ISSUE THREAD

**Issue by kvijai82** [kabanero-io/kabanero-pipelines#179]

**Comment by kvijai82** [comment]
Have discussed this with the test team and a nightly build test framework is expected to be available mid April.  The plan for now is for each team to investigate their preferred test framework and write tests.  We will have a guide to integrate these into the main test framework in a few weeks.

**Comment by aadeshpa** [comment]
This issue is broad level issue for the test framework and below is the specific issue under kabanero-foundation repository:
https://github.com/kabanero-io/kabanero-foundation/issues/200

**Comment by aadeshpa** [comment]
Closing this issue as Kabanero test team is defining this framework.
