### ISSUE TITLE
Adopt the Open Liberty Operator

### ISSUE THREAD

**Issue by arthurdm** [kabanero-io/kabanero-pipelines#183]
Once the Open Liberty Operator is adopted by Appsody (via issues [601](https://github.com/appsody/stacks/issues/601) and [824](https://github.com/appsody/appsody/issues/824)) and Kabanero (via issue [126](https://github.ibm.com/IBMCloudPak4Apps/icpa-roadmap/issues/126)) there will be `app-deploy.yaml` files that have `Kind: OpenLibertyApplication` coming through the pipeline.

Functionality there shouldn't be any updated needed from the pipelines, as it is relying on the appsody stack to already have the `app-deploy.yaml` file or for the appsody CLI to generate one.  So I am opening this for awareness of the pipeline team, and for the addition of new tests that use `Kind: OpenLibertyApplication`.

You can take existing `Kind: AppsodyApplication` , just change the `Kind` and everything should work the same way.  

We have added new functionality, such as day-2 operations, but those are not meant to be triggered by the pipeline (at least not yet).

**Comment by marikaj123** [comment]
@arthurdm - Was the work completed in Kabanero 0.6.0 or is it moved to a later release?

**Comment by arthurdm** [comment]
@marikaj123 - it will be included in Kabanero 0.7.0

**Comment by arthurdm** [comment]
The last piece for this work is https://github.com/appsody/stacks/issues/721

**Comment by marikaj123** [comment]
@kvijai82 - Is the issue ready to close?

**Comment by kvijai82** [comment]
This has been manually tested.
