### ISSUE TITLE
Move up to Tekton 0.10.1 pipeline and Triggers 0.2.1

### ISSUE THREAD

**Issue by anneqm** [kabanero-io/kabanero-pipelines#188]
Need to move up to Tekton 0.10.1 pipelines release and Triggers 0.2.1 release for Kabanero 0.6.0
Note syntax change for Triggers called out separately in https://github.com/kabanero-io/kabanero-pipelines/issues/165.

**Comment by anneqm** [comment]
@kvijai82 @brianxjx  Dev previews are available for openshift/tektoncd-pipelines 0.10.1 and openshift/tektoncd-triggers 0.2.1 if that would be of help to get started with. We were notified in the Tekton slack workspace yesterday.

**Comment by kvijai82** [comment]
Thanks @anneqm.  We are in the process of trying to consuming it and testing.  Will let you know if we find issues.

**Comment by kvijai82** [comment]
Picked up and updated pipelines to work with the tekton releases mentioned above.
