### ISSUE TITLE
Update "validate-collection-is-active" step to support multi-versioned stacks

### ISSUE THREAD

**Issue by smcclem** [kabanero-io/kabanero-pipelines#196]
Multiple version of a given stack can be activated at a given time.  The default pipeline for each stack contains sample pipelines that includes a step validate-collection-is-active, to make sure the stack that is being built is active.  

This step currently take the image value from the git-source .appsody-config.yaml, and compares that value against the list of images that have been activated to determine if the build can proceed. 

The issue we seek to fix is that appsody only includes two digits (major.minor) in their image specification with .appsody-config.yaml, which means at pipeline build time,  we cannot disambiguate between versions of stack because we do not have a third digit/patch (major.minor.patch) version number.  

Therefore we want to implement this check algorithm to be able to enforce only building active version of the stack:

1. Parse .appsody-config for user, repo, STACKNAME, VERSION 2 digit)
1. Issue oc get stack ,  get **3 digit** version number(s) for active STACKNAME
1. Query image registry to get sha256 for tag "VERSION"
1. Query image registry to get sha256 for version(s) tag(s) from step 2 
1. The sha256 obtained in step 3 must be included in the sha256 list obtained in step 4 for the build to proceed

Future improvement will include the Kabanero operator caching the sha256 from the image registry at the time the stack(s) are activated.  This means step 4 will get the sha256 list from the CR instead of querying the image registry.

**Comment by marikaj123** [comment]
According to Scott some of the work will go into 0.6.0 and the rest in 0.7.0.

**Comment by marikaj123** [comment]
@smcclem - Is the issue ready to close?

**Comment by smcclem** [comment]
https://github.com/kabanero-io/kabanero-pipelines/pull/204/files
