### ISSUE TITLE
Document & test pipeline curation

### ISSUE THREAD

**Issue by jgawor** [kabanero-io/kabanero-pipelines#201]
Document how pipelines are cloned, modified, released and made available to Kabanero when using GitHub Enterprise. Basically, the whole process when starting from this repository.

**Comment by marikaj123** [comment]
@jgawor - Any particular release the work is expected to be completed?

**Comment by brianxjx** [comment]
We have improved the provided Readme and tested the described steps therein.

**Comment by brianxjx** [comment]
https://github.com/kabanero-io/kabanero-pipelines/blob/master/ci/tekton/README.md

**Comment by brianxjx** [comment]
@jantley-ibm   Is this README something you would reference (or copy) as for a guide tile?

**Comment by jantley-ibm** [comment]
@brianxjx there are a number of new guides related to pipelines that need to be written; @kvijai82 can speak more to this point. The more of this type of content that we can move up into guides, the better.  Create issues in the /docs repo for new guides that need to be created so we can assign and track them; tag with "guide" and "documentation-id".

**Comment by marikaj123** [comment]
Vijai created the following issue for the guide: https://github.com/kabanero-io/docs/issues/333

**Comment by kvijai82** [comment]
Closing this issue as the doc is now published in the pipelines repo and a corresponding issue has been opened in the doc repo to convert it to a guide.
