### ISSUE TITLE
Bug: push step failing when using private registry

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-pipelines#224]
I am trying the pipeline run with custom own stack which use private registry. Validation is working correctly for that but the push step failed:

Secret for the private registry is created.

```
Running command: buildah pull docker.io/kabsvt/svt-springboot:0.3
Error initializing source docker://kabsvt/svt-springboot:0.3: Error reading manifest 0.3 in docker.io/kabsvt/svt-springboot: errors:
denied: requested access to the resource is denied
unauthorized: authentication required
```

**Comment by mtamboli** [comment]
@marikaj123 FYI

**Comment by kvijai82** [comment]
I think this should be fixed in rc.5

**Comment by marikaj123** [comment]
According to Monica it passed verification and can be closed.
