### ISSUE TITLE
Bug: Validation of stacks fails when the latest version is not active

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-pipelines#234]
With new validation design, if the kabanero instance is using a stack hub which has older version of stack, validation will fail.

I think this will cause issues. Here is the scenario I am thinking:

Any Kabanero instance in customer environment using default stack hub will fail when new version of stack becomes available.
If customers configured 0.6.0 kabanero with default stack hub. When with kabanero 0.7.0, a new stack version is checked in, all old deployed Kabanero projects will start failing. So you will have to use 0.7.0 stack hub with 0.6.0 kabanero instance?

**Comment by mtamboli** [comment]
After team have have discussion on this defect, we can re-assess the stop-ship status.

**Comment by kvijai82** [comment]
Updated the task to not fail on version checks for now.  It will print out a warning like below.  Other high level validation checks will still fail the task and the pipeline.  Plan is to revisit the whole digest checking design in 0.8.0.

```Git project config in .appsody-config.yaml... 
VERSION = 0.2.21
STACK_IMAGE_REGISTRY = docker.io
PROJECT = kabanerobeta
STACK_NAME = java-microprofile
RECONCILED_STACK_IMAGE_REGISTRY_HOST = docker.io

In the cluster...
STACK_IMAGE = docker.io/kabanerobeta/java-microprofile
STACK_IMAGE_REGISTRY = docker.io
PROJECT = kabanerobeta
STACK_NAME = java-microprofile
VERSIONS = 0.2.25

Cluster stack version: 0.2.25, Cluster stack digest: "sha256:4d6b7c2f0a2818aab4e9abbf256f28dc9d3c8b3fc783000b9e173f3172890e94"
Project stack version: 0.2.21, Project stack digest: "sha256:e04c83ec2c7efb796a31d1b85f86dc4816ee5269e4a5764896a3b7065a16ee13"
WARNING: A compatible version of the application stack, docker.io/kabanerobeta/java-microprofile:0.2.21, is not active on this cluster. Please review the active versions of the stack on the cluster (oc get stack java-microprofile -o json) and the stack specification in the .appsody-config.yaml file of the git project.```

**Comment by marikaj123** [comment]
it is verified and Monica is looking to close it.

**Comment by mtamboli** [comment]
Verified this with rc.9 pipelines.
