### ISSUE TITLE
Consolidate duplicted step of `imagename-lowercase` from multiple task to a separate task

### ISSUE THREAD

**Issue by aadeshpa** [kabanero-io/kabanero-pipelines#235]
We introduced the step `imagename-lowercase` to make the image name as lowercase, which is passed by the user, however to make the imagename as lowercase and keep tag name as it is, we had to do string manipulation steps in this step.
Since this is required in all the tasks build-push, build and build-deploy tasks , it is duplicated. 

We need to make this step `imagename-lowercase` as a separate task.

**Comment by aadeshpa** [comment]
We have created this PR with the fix https://github.com/kabanero-io/kabanero-pipelines/pull/248
Currently testing the changes by running the pipelines.

**Comment by kvijai82** [comment]
Merged PR.
