### ISSUE TITLE
Update tasks / pipelines / triggers to use the appropriate Tekton pipeline version - 0.10.8

### ISSUE THREAD

**Issue by marikaj123** [kabanero-io/kabanero-pipelines#239]
Update the pipeline code to move to the appropriate Tekton pipeline version.

**Comment by marikaj123** [comment]
Hi @anneqm - Please inform us of the version of Tekton that needed to be used by the pipeline team.

**Comment by anneqm** [comment]
@marikaj123  We should only be moving up when the openshift-pipelines-operator moves up.  As of right now, we have tekton pipelines 10.1, which is still the latest. I do see that openshift-pipelines-operator has a new 0.10.6 release, don't know if there would be value in moving to that from the 0.10.4 version kabanero 0.6 is on.  The next version of Tekton pipelines 0.11 has not yet been released by the Tekton community. Will keep you posted.

**Comment by kvijai82** [comment]
@anneqm @marikaj123 Since we only have a couple of days left in 0.7.0 and there isin't a new release available, can I move this to 0.8.0?

**Comment by marikaj123** [comment]
Yes, I think it is a good idea for move it to release 0.8.0.

**Comment by anneqm** [comment]
Tekton pipelines v0.11.x should be released this week.. There will be no time to move up.. please plan this for 0.8.0.

**Comment by marikaj123** [comment]
@kvijai82 - Are we staying with Tekton pipleine 0.10.1 for Kabanero 0.8.0?  As we are close to providing the release candidate this week and the beta pipeline is not been release yet.
