### ISSUE TITLE
Determine how to access tekton dashboard endpoints over https

### ISSUE THREAD

**Issue by kvijai82** [kabanero-io/kabanero-pipelines#24]
Our doc suggests a couple of curl commands against the tekton dashboard to register the webhook.  This was written when the dashboard did not require credentials or supports https.  With the new version of the dashboard requiring https and authentication, determine how we handle those requirements and update the doc.

**Comment by kvijai82** [comment]
@jtmulvey thanks for helping with this.  Assigning to you for now.  Please reassign to whoever with the appropriate security expertise can help.

**Comment by mnuttall** [comment]
Please use openshift-tekton-dashboard.yaml attached to the https://github.com/tektoncd/dashboard/releases to get HTTPS access to the dashboard.

**Comment by mnuttall** [comment]
We're working to improve the clarity of the dashboard docs in this area.
