### ISSUE TITLE
Pipeline ignores appsody build error

### ISSUE THREAD

**Issue by jgawor** [kabanero-io/kabanero-pipelines#245]
Running the `build-deploy-pl` pipeline. The `push` step failed to deploy an image that was supposed to be built in the `build` step but it wasn't. Looking at the `build` step, the `appsody` command failed but the task kept on executing.  

```
[Buildah] STEP 9: COPY --from=compile /project/user-app/config/ /work/config/
[Buildah] error building at STEP "COPY --from=compile /project/user-app/config/ /work/config/": no files found matching "/var/lib/containers/storage/overlay/a2f1f0053ea1617a654e78f2a0ba76efc870c7c90017b970ebd732187487aad8/merged/project/user-app/config": no such file or directory
[Error] exit status 1
Copying the generated app-deploy.yaml file from input to the output to pass the file to the next task when this task is used in deploy pipeline
```

The task should fail as soon as error is detected.

**Comment by marikaj123** [comment]
According to Jarek, this issue is not for 0.6.0.

**Comment by marikaj123** [comment]
@kvijai82 - At what Kabanero release would the fix become available?

**Comment by aadeshpa** [comment]
This issue will be fixed in 0.9.0.rc2 as per @kvijai82

**Comment by aadeshpa** [comment]
This issue fix is in the PR :  https://github.com/kabanero-io/kabanero-pipelines/pull/357.
Once this is merged, we can mark this issue as closed.

**Comment by aadeshpa** [comment]
Marking this issue as resolved. PR is merged
