### ISSUE TITLE
Trim trailing / of configured registry

### ISSUE THREAD

**Issue by dacleyra** [kabanero-io/kabanero-pipelines#251]
Pipeline and/or Tekton should trim trailing / of configured registry

Setting the registry with a trailing / such as the following causes failure: image-registry.openshift-image-registry.svc:5000/kabanero/ 

With pipelines release
https://github.com/kabanero-io/kabanero-pipelines/releases/download/0.6.0/default-kabanero-pipelines.tar.gz

```
{"level":"info","ts":1583432835.921106,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
OUTPUTS_RESOURCE_DOCKER_IMAGE_URL_LOWERCASE=image-registry.openshift-image-registry.svc:5000/kabanero//sample-java-microprofile:e923b666fc3dedbfb6f635efbfc8eaf77eaebbf0
invalid reference format
```

**Comment by aadeshpa** [comment]
Pull request created with the fix : https://github.com/kabanero-io/kabanero-pipelines/pull/256

**Comment by kvijai82** [comment]
Fix is merged.
