### ISSUE TITLE
Epic: GitOps support

### ISSUE THREAD

**Issue by mnuttall** [kabanero-io/kabanero-pipelines#255]
This work leads on from CLI development taking place under https://github.ibm.com/hybrid-devops/DevOps/issues/41. A more public home for the CLI development work should become available in due course. 

Two new features are required in the Pipeline:
- An extended 'build' task 
- A simple deployment task

Our existing Tekton build pipeline must be extended to support the GitOps mode of operation. I.e. the command line tool from DevOps-41 must be packaged into a Tekton task and appended to the end of the existing docker build / docker push Pipeline that runs when changes are merged, so that it becomes docker build / docker push / promote [to dev]. 

Deployment-only Tekton Pipeline: Deployment may be performed by Tekton, ArgoCD, or other Kustomize-friendly tools. A Tekton Task and Pipeline must be developed so that we provide a default, Tekton out of the box option for deployment. This is basically `kubectl apply -k [env].` All environments will be namespaces in a single cluster, and it's the same cluster as Kabanero is installed into.

**Comment by marikaj123** [comment]
@mnuttall - Does this issue need to be turned into an Epic?  Does it need to be targeted to a particular release?

**Comment by kvijai82** [comment]
Will need to apply the tag that was pushed into the deployment yaml - CLI will support it and will be called by the task.

Might potentially have a different branch with config for each env or a repo for each env like dev, prod etc.

**Comment by anneqm** [comment]
@marikaj123 This needs to target Kabanero 0.9.0 release. Would you please add the release tag?  @kvijai82 Any estimate for how long this will take?  Per @mnuttall, we plan to have the pre-requisites for the pipeline team to get started within two to three weeks.

**Comment by marikaj123** [comment]
@kvijai82 - According to Ann:  Anne's team is going to complete the containment exercise that it is contained, assuming Vijai et al can use the cli piece Anne's team is developing then and it all comes together in time for kab 0.9.

**Comment by marikaj123** [comment]
Id may be needed in Kabanero 0.9.0.

**Comment by mnuttall** [comment]
Please see my note, 'ICPA GitOps: 'promote' cli functional; Pipeline work under kabanero-pipelines-255 unblocked' sent today, April 7th.

**Comment by ianpartridge** [comment]
An idea from @matthewpwilson .. it would be good to include some validation of the GitOps repo before applying it.. something like:

`kubectl apply -k --dryrun`

**Comment by anneqm** [comment]
@kvijai82 Vijai, do you have everything needed to get started with this piece? Per comment from @mnuttall above ^^ and in email reference April 7.  Please let us know if you need anything else to get started.

**Comment by kvijai82** [comment]
@anneqm yes we have enough enough to get going.  Mark & Ian gave us a lot of good info.  We started on it a couple of days back and plan to meet with Mark tomorrow to dicuss further.

**Comment by marikaj123** [comment]
@kvijai82 - In the Planning workspace, please keep this Epic under the Epic pipeline for tracking purposes. Thank you.

**Comment by aadeshpa** [comment]
Based on the discussion with @kvijai82 we look green on this epic for the release.

**Comment by aadeshpa** [comment]
@kvijai82 : cut the pipelines release 

For gitops
url: https://github.com/kabanero-io/kabanero-pipelines/releases/download/0.9.0-rc.1/kabanero-gitops-pipelines.tar.gz
sha256: 8c443103a36f961777969a9a297680bf7be4deb63f584ce007760d480c21ae60

**Comment by kvijai82** [comment]
Delivered the pipelines needed in 0.9.0-rc.1.  Will address any further things that come up in new issues.
