### ISSUE TITLE
Bug: Use of config Map confusing for users #360

### ISSUE THREAD

**Issue by marikaj123** [kabanero-io/kabanero-pipelines#257]
(Originator of the issue) According to @mtamboli - I  agree that Champ would most likely use private registry and major change not a good idea being that late in the release cycle. So with that in mind, we can just improve this message The application stack, docker.io/kabanero/java-spring-boot2:0.3, in .appsody-config.yaml is active on this cluster and can be built. to indicate user that we ignoring the value defined in .appsody-config.yaml for this special case when using external route of internal registry and print the stack that is actually active and will be used.

(Owner if the issue) According to t Vijai: 
@mtamboli yes I will make that change to the message and cut a new RC.

**Comment by kvijai82** [comment]
Created RC3 of pipelines with the fix.  Will wait for @mtamboli to test before closing.

**Comment by mtamboli** [comment]
@marikaj123 I checked 
```

Git project config in .appsody-config.yaml... 
VERSION = 0.3
STACK_IMAGE_REGISTRY = docker.io
PROJECT = kabanero
STACK_NAME = java-spring-boot2

WARNING - .appsody-config.yaml specifies different repository, docker.io, than what's configured in the config map, image-registry.openshift-image-registry.svc:5000, in the cluster.  Config map entry takes priority.  Using image-registry.openshift-image-registry.svc:5000 as the default stack registry.
RECONCILED_STACK_IMAGE_REGISTRY_HOST = image-registry.openshift-image-registry.svc:5000

.....

WARNING - A config map has been created on the cluster with the stack image registry information. The registry of the application stack, docker.io/kabanero/java-spring-boot2:0.3, specified in .appsody-config.yaml will be overridden by the registry configured in the config map, stack-image-registry-map.
Validation is performed using the image located in the image-registry.openshift-image-registry.svc:5000 registry that was configured in the config map.

The application stack, kabanero/java-spring-boot2:0.3, in .appsody-config.yaml is active on this cluster and can be built.

```

**Comment by mtamboli** [comment]
We can close this after the latest pipeline is picked up by the operator.

**Comment by marikaj123** [comment]
Closing the issue as it was verified successfully by SVT.
