### ISSUE TITLE
Ensure that the tekton dashboard validates the secret sent by git

### ISSUE THREAD

**Issue by kvijai82** [kabanero-io/kabanero-pipelines#26]
When the tekton dashboard registers a webhook with git, it should send a shared secret that git will include in the future requests to the dashboard.  Ensure that the dashboard is sending this secret to git during the webhook registration process and validates it properly when git makes the call to drive a pipeline.

**Comment by kvijai82** [comment]
@jtmulvey just FYI.  Opening this here so I can keep track of all the webhook related issues under one epic. Think you mentioned you were going to be discussing this with Mark this week.

**Comment by mnuttall** [comment]
This is currently handled by virtue of our using the Knative Webhooks sample, https://knative.dev/docs/serving/samples/gitwebhook-go/

**Comment by kvijai82** [comment]
Closing based on Mark's comment that this is handled.
