### ISSUE TITLE
Write a guide explaining how to use a pipeline to build & deploy an app

### ISSUE THREAD

**Issue by kvijai82** [kabanero-io/kabanero-pipelines#282]
This would also cover using the OCP internal registry with the external route.

**Comment by mingcyu** [comment]
@kvijai82 Hi Vijai, are you on track to completing by the end of the week(friday, May 1st)?

**Comment by kvijai82** [comment]
@mingcyu yes I have the first pass done.

**Comment by kvijai82** [comment]
The following guide will walk you through the steps needed to run a pipeline to build your application, publish the image to a registry, and optionally deploy the application on your cluster.

1. Clone the `kabanero-pipelines` repo.
    - cd into the pipelines/sample-helper-files directory.
2. For this guide, we will use the one of the default pipelines, `java-ol-build-deploy-pl`, that is activated by the Kabanero operator.  You can replace this with any of the other build-deploy-pl or your custom pipeline.
3. Make sure you have the appropriate storage setup to drive Tekton pipelines.  If you have a dynamic storage provisioner available on your cluster there is nothing to do.  If not you can setup a simple NFS babsed PV using the nfs-pv.yaml sample provided.
    - Run `oc apply nfs-pv.yaml`
4. Create the secret for your github repo. You can skip this step if it's a public repo. For a private repo, follow the steps in `Secrets` section of https://kabanero.io/guides/working-with-pipelines/#getting-started.
5. Create the secret for your registry.  
    - If you are using the internal route of the internal registry of your OCP cluster, you do not have to configure a secret as long as the service account you are running the pipeline with has the right permissions.  The `kabanero-pipeline` service account is setup with the appropriate permissions.
    - If you are using the external route of the internal registry of your OCP cluster, you do not have to configure a secret also as the pipeline will recognize the URL and translate it to the internal route of the registry automatically.
    - If you are using a private registry, follow the steps in `Secrets` section of https://kabanero.io/guides/working-with-pipelines/#getting-started to setup a secret for your registry.
6. Setup certificates or specify insecure connection for the registry access following the documentation in https://kabanero.io/guides/working-with-pipelines/#transport-layer-security-tls-verification-for-image-registry-access-in-pipelines.
7. Run the pipeline.  There are multiple ways to do this.  Please reference the `https://kabanero.io/guides/working-with-pipelines/#running-pipelines` documentation and choose the method you would like to follow to run the pipeline.
8. Review the status of your run and logs using the documentation provided at https://kabanero.io/guides/working-with-pipelines/#checking-the-status-of-the-pipeline-run
9. When the pipeline run is complete, you can go to your registry to check if the application image is published.
10. If you ran the pipeline via the webhook, it will only deploy the application if you initiated the run via a pull request merge. If that's the case, continue to the next step to access your application.
11. You can run `oc get apposodyapplications` or check your pods to see your application pod running.
12. You will have to create a secret for your registy and associate it with the new service account that was created by the appsody application for your application.
    - If you are using the internal route for the internal registry there is nothing to do as the service account has the necessary permissions.
    - For private registries and the external route of the internal registry, create the secret for your registry and link to the service account that matches your application name.
13. If you exposed a route for your application, check the routes (`oc get routes` for example) and test your application.

**Comment by aadeshpa** [comment]
@kvijai82 has opened an issue in docs repo for this guide to be updated: https://github.com/kabanero-io/docs/issues/403

**Comment by kvijai82** [comment]
Delivered content to doc team
