### ISSUE TITLE
Develop deploy pipeline to target either test or production target

### ISSUE THREAD

**Issue by ralanlittle** [kabanero-io/kabanero-pipelines#3]

**Comment by kvijai82** [comment]
After discussions with Alan, we will be shipping a single pipeline that illustrates build & deploy to the local cluster in this milestone.  This might be something we tackle down the road.

**Comment by tseelbach** [comment]
@ralanlittle we are targeting epic #1, 2, and 4 in 19.17.   Can we kick this epic  (#3) out, or close it?

**Comment by kvijai82** [comment]
For now split up the pipeline into build & deploy pipelines.  The deploy pipeline will need to deploy into a specified namespace.  Alan / Steve determining how the namespace will provided.

**Comment by kvijai82** [comment]
Working on this under https://github.com/kabanero-io/roadmap/issues/94
