### ISSUE TITLE
What is the purpose of creating an image for your pipelines?

### ISSUE THREAD

**Issue by oiricaud** [kabanero-io/kabanero-pipelines#308]
Not sure if there is a form where I can post this question, but what are the main benefits of creating an image of your pipelines? I noticed in Kabanero 0.6 there are 3 scripts `env.sh` `package.sh` and `release.sh`, in the `env.sh` if you put your docker username and password it pushes your pipelines to docker hub. I am just wondering why is this needed? And what are the main benefits as opposed to create a release on github?

https://hub.docker.com/repository/docker/yellocabins/pipelines-index

https://github.com/oiricaud/pipelines

**Comment by kvijai82** [comment]
The docker image that is being created is one that can serve the pipeline(s) archive.  It is an edge case scenario where, for reasons of your own, you can choose not to have git host and serve the pipeline(s) archive and instead deploy an NGINX container which will serve them.

**Comment by oiricaud** [comment]
Thanks!
