### ISSUE TITLE
Switch image tags to digests

### ISSUE THREAD

**Issue by jgawor** [kabanero-io/kabanero-pipelines#309]
Switch all image references from tags to digests. This is required for air gap installs. 

In OpenShift environment, image mirroring can be set up so that even if operator references image from registry A, the actual image is pulled from registry B. This mirroring is only supported for image references using digests. More information on https://docs.openshift.com/container-platform/4.3/openshift_images/image-configuration.html#images-configuration-registry-mirror_image-configuration

**Comment by aadeshpa** [comment]
PR is ready for this issue : https://github.com/kabanero-io/kabanero-pipelines/pull/373

**Comment by aadeshpa** [comment]
Above PR is merged. Assigning this issue to @kvijai82 for changes in Gitops and Eventing pipelines changes.

**Comment by kvijai82** [comment]
Fixes in rc4
