### ISSUE TITLE
Provide a complete list of images

### ISSUE THREAD

**Issue by jgawor** [kabanero-io/kabanero-pipelines#310]
Provide a complete list of images in the [CASE metadata format](https://github.com/IBM/case/blob/master/210-resources.md#container-images). This is required for air gap installs and needs to be done/updated for each release.

**Comment by aadeshpa** [comment]
what's important to remember is we will need to keep this up-to-date for each icpa release

meaning, it's going to be an ongoing task - not a single hit

@jgawor has opened this issue for creating a place for this information.

https://github.ibm.com/IBMCloudPak4Apps/icpa-install/issues/638

**Comment by aadeshpa** [comment]
containerImages:
  - image: kabanero/kabanero-utils
    mediaType: application/vnd.docker.distribution.manifest.v2
    tag: 0.9.0
    digest: sha256:8020573657ed1b80e2b872a37719d6398ee78219296fe6180733f54425f7bd6a
    platform:
      architecture: amd64
      os: linux
    registries:
      - host: docker.io
  - image: kabanero/scanner
    mediaType: application/vnd.docker.distribution.manifest.v2
    tag: 1.3.1
    digest: sha256:82b979de485fc5990d41b8b4acc2aeee2211bd26b0f03374f5657773ae4148f9
    platform:
      architecture: amd64
      os: linux
    registries:
      - host: docker.io

**Comment by aadeshpa** [comment]
NOTE:
1. To find the above information you can follow steps
docker pull [imagename@sha256:xyz]
docker inspect [imagename@sha256:xyz]

2. Above inspect provides you all the details except the `mediaType ` and for that you need to enable manifest inspect experimental cli function for docker on your machine

`export DOCKER_CLI_EXPERIMENTAL=enabled`
docker manifest inspect  [imagename@sha256:xyz]

**Comment by aadeshpa** [comment]
marking it as closed
