### ISSUE TITLE
Move scripts generated by utilities task into the kabanero-utils image

### ISSUE THREAD

**Issue by kvijai82** [kabanero-io/kabanero-pipelines#313]
This will prevent us from having to copy it from task to task and also improve the overall pipeline performance.

Also update all the tasks to remove the script copy commands.

**Comment by aadeshpa** [comment]
We did this change in two different PR
PR1 : https://github.com/kabanero-io/kabanero-pipelines/pull/335

PR2: https://github.com/kabanero-io/kabanero-pipelines/pull/336

**Comment by aadeshpa** [comment]
Both the PR are merged . marking this as closed.
