### ISSUE TITLE
Pipeline update for Converge on common developer tools - Odo/Devfiles 

### ISSUE THREAD

**Issue by marikaj123** [kabanero-io/kabanero-pipelines#323]
Epic: Converge on common developer tools - Odo/Devfiles 156

**Comment by anneqm** [comment]
@tseelbach @marikaj123 also consider the question:  Need to update the pipeline to use devfiles, is it just a matter of porting current pipeline or do we need new pipelines for each stack?

**Comment by tseelbach** [comment]
not doing in Kabanero at this time
