### ISSUE TITLE
ensure pipeline support Quarkus

### ISSUE THREAD

**Issue by tseelbach** [kabanero-io/kabanero-pipelines#328]
hopefully "just another Stack"

**Comment by marikaj123** [comment]
@tomlinkusa and @kvijai82 - Kabanero 0.9.0 stack-Hub is going to include Quarkus as a tech preview. Do we need any work from the pipeline to support it?

**Comment by tomlinkusa** [comment]
Perhaps to add new tests. Otherwise I don't know. Get @garypicher @stevenschader @StringCheeseCR to weigh in.

**Comment by kvijai82** [comment]
Based on discussion with Arthur, this should just work as is like other stacks.  Do a manual test this week at some point.

**Comment by brianxjx** [comment]
090rc.1 for Kabanero Operator & Pipelines manual test successful.
