### ISSUE TITLE
Update pipelines docs to reflect new pipelines & tasks

### ISSUE THREAD

**Issue by kvijai82** [kabanero-io/kabanero-pipelines#360]
Update the working with pipelines guide to mention gitops, events pipelines.
Also add deprecation notice for incubator pipelines and link to events guide.

**Comment by mingcyu** [comment]
@kvijai82 @aadeshpa  Can you let us know when a draft can be provided? We GA this Friday

**Comment by kvijai82** [comment]
@mingcyu apologize for the delay.  We have some late feature we are still trying to sort out that will afffect this doc.  I have a draft mostly there and will create the issue in the doc repo once we settle on the gitops pipelines for events by tomorrow.

**Comment by jantley-ibm** [comment]
Completed in https://github.com/kabanero-io/guides/pull/63, closing
