### ISSUE TITLE
Deploy from environment instead of env in deploy-kustomize pipeline

### ISSUE THREAD

**Issue by kvijai82** [kabanero-io/kabanero-pipelines#362]
Based on design changes from RH

Impact on Pipelines
 
The deployment pipeline currently uses
 
kubectl apply -k env
 
This needs to change to
 
kubectl apply -k environments
 
This will work due to the /environments/kustomization.yaml change added in Solution Builder.

**Comment by kvijai82** [comment]
Fixed in rc4

**Comment by aadeshpa** [comment]
This is merged in 0.9.0-rc5 of pipelines, so marking it as closed.
