### ISSUE TITLE
Missing event-listener-role-binding in kabanero namespace

### ISSUE THREAD

**Issue by mchenggit** [kabanero-io/kabanero-pipelines#363]
New  event listeners created as part of eventing pipeline now run in kabanero namespace, in addition to the event listener created by Tekton webhook extension that runs in the tekton-pipelines namespace. An additional rolebinding is needed in kabanero namespace.

**Comment by marikaj123** [comment]
https://github.com/kabanero-io/kabanero-pipelines/issues/363

**Comment by kvijai82** [comment]
Submitted PR to operator for this https://github.com/kabanero-io/kabanero-operator/pull/709.  Will close this out once it's verified in next operator RC

**Comment by aadeshpa** [comment]
The new Rc.4 release of the operator is cut, which has this fix.

**Comment by aadeshpa** [comment]
closing it for now.
