### ISSUE TITLE
Correct pre-deploy task name

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-pipelines#383]
Currently, pre deploy task is being called  `enforce-stack-policy-post-build` instead of something like `enforce-stack-policy-pre-deploy`?

**Comment by aadeshpa** [comment]
@mtamboli : The fix for this issue is in 0.9.0-rc.6 of pipelines, can you please verify once and mark it as closed.

**Comment by mtamboli** [comment]
Verified that this is fixed.
