### ISSUE TITLE
deploy-kustomize --dryrun=server

### ISSUE THREAD

**Issue by tnixa** [kabanero-io/kabanero-pipelines#391]
Using the new kabanero `deploy-kustomize` pipeline for the `baristahttp` coffeeshop microservice and the deploy step is failing due to the `coffeeshop-dev` namespace not being there...
```
[INFO] Starting dry run...
I0520 16:40:41.486229      12 request.go:621] Throttling request took 1.147718634s, request: GET:https://172.30.0.1:443/apis/apiextensions.k8s.io/v1beta1?timeout=32s
namespace/coffeeshop-dev created (server dry run)
Error from server (NotFound): error when creating "/workspace/git-source/environments": namespaces "coffeeshop-dev" not found
Error from server (NotFound): error when creating "/workspace/git-source/environments": namespaces "coffeeshop-dev" not found
Error from server (NotFound): error when creating "/workspace/git-source/environments": namespaces "coffeeshop-dev" not found
[ERROR] Dry run of deployment was unsuccessful. Please review errors above for more details. Service will not be deployed.
```
comments from Ian Partridge:
"they’re passing --dry-run=server
That probably explains it… the server validation for each API request is probably checking that the namespace exists, and it doesn’t (because it’s a dry run) so it fails
We should try with just --dry-run"

**Comment by matthewpwilson** [comment]
The general problem is described here: kubernetes/kubernetes#83562 - each resource is applied independently. Therefore a server dry run including a namespace will never work.

**Comment by tnixa** [comment]
@kvijai82 changed it to `dryrun=client` and we also are instructing users to create the namespace manually
