### ISSUE TITLE
deploy running immediately after promote without merging

### ISSUE THREAD

**Issue by tnixa** [kabanero-io/kabanero-pipelines#392]
I have three coffeeshop microservice repos setup with webhooks to run the `build-push-deploy` pipeline and then i have three devops repos setup with webhooks to run the `deploy-kustomize`. When I run the new `build-push-deploy` pipeline the `deploy-kustomize` pipeline runs immediately after. I believe the correct behavior is the `deploy-kustomize` should only run after the devops PR is merged. 
@kvijai82 was going to check with the tekton team about this, "Maybe I need to have a conditional check before driving deploy"

**Comment by kvijai82** [comment]
Added a conditional check before driving deploy pipeline to only execute the task for push to master.

**Comment by tnixa** [comment]
Not seeing this anymore with the changes from @kvijai82
