### ISSUE TITLE
deploy-kustomize pipeline randomly doesn't work when both gitops & events pipelines are activated

### ISSUE THREAD

**Issue by kvijai82** [kabanero-io/kabanero-pipelines#399]
[I] ➜ oc -n kabanero logs deploy-kustomize-pl-d0d281-deploy-kustomize-task-dltlj-de-2q9t7 -c step-deployment-condition
Checking if deploy step should execute...
/bin/sh: line 1: params.event-type: command not found
/bin/sh: line 2: params.event-ref: command not found
/bin/sh: line 3: params.event-type: command not found

**Comment by ianpartridge** [comment]
I see this problem using `0.9.1-alpha.3` event pipelines.

**Comment by ianpartridge** [comment]
I see the pipeline pass because the `deploy` step is skipped.

![image](https://user-images.githubusercontent.com/1423497/83929129-3da88080-a78a-11ea-80e4-d7dd69291ee8.png)

**Comment by aadeshpa** [comment]
Fix is in 0.9.1-rc.3
