### ISSUE TITLE
Integrate Security steps in pipelines

### ISSUE THREAD

**Issue by ralanlittle** [kabanero-io/kabanero-pipelines#4]
scan of the container we are building and publishing

**Comment by kvijai82** [comment]
Depends on https://github.com/kabanero-io/kabanero-security/issues/2 & https://github.com/kabanero-io/kabanero-security/issues/3

**Comment by marikaj123** [comment]
Building a container for the Scan, going into a sample pipeline. Describe and doc how to do scanning a Tekton pipeline.

**Comment by marikaj123** [comment]
According to the security team, they may need more time to complete the appropriate work needed by security issues, listed above.

**Comment by marikaj123** [comment]
@tseelbach and @jtmulvey - As per the agreement, moving the Epic out of this release.

**Comment by marikaj123** [comment]
Looking to complete security issue 2 in v0.3.0: kabanero-io/kabanero-security#2 
Will try to complete issue 3 in v0.3.0:  kabanero-io/kabanero-security#3

**Comment by kvijai82** [comment]
We have a container scan that's working now.  We have some improvements to make in how it's reporting results in the next release.  Will complete final tests and create a PR for this tomorrow.

**Comment by kvijai82** [comment]
Changes pushed to collections and the scan task is available in the latest collections release.
