### ISSUE TITLE
Use Razee to propagate production builds downstream

### ISSUE THREAD

**Issue by ralanlittle** [kabanero-io/kabanero-pipelines#5]

**Comment by kvijai82** [comment]
Not targeting this for present milestone.  @ralanlittle to have further discussions with other folks to see if this a path we want to go down.

**Comment by tseelbach** [comment]
@marikaj123 this is not in 19.17

**Comment by kvijai82** [comment]
No doing Razee for the time being.  Will reopen when we decide to do this again.
