### ISSUE TITLE
Create doc / blogs / videos explaining how to run & debug pipelines

### ISSUE THREAD

**Issue by kvijai82** [kabanero-io/kabanero-pipelines#51]

**Comment by kvijai82** [comment]
We created some videos in 19.18.  Plan to work on a blog in 19.19 and make some doc updates.

**Comment by mingcyu** [comment]
@kvijai82 Hi Vijai, is documentation[editorial and review] support needed for this item?

**Comment by marikaj123** [comment]
@kvijai82 - To have the content reviewed by Alan/Nate, please create a PR and assign it to them as reviewers.  Thank you.

**Comment by kvijai82** [comment]
Created the required docs in https://github.com/kabanero-io/docs/issues/56 and linked the videos to that.
