### ISSUE TITLE
Serviceability: build-step modify-yaml & install-knative should print if YAMLFILE not found

### ISSUE THREAD

**Issue by groeges** [kabanero-io/kabanero-pipelines#57]
@dacleyra commented on [Tue Aug 06 2019](https://github.com/kabanero-io/kabanero-collection/issues/44)

Pick up result of
https://github.com/appsody/tekton-example/issues/19

---

@marikaj123 commented on [Mon Aug 12 2019](https://github.com/kabanero-io/kabanero-collection/issues/44#issuecomment-518790367)

Summary of the work:
The collection defines the pipeline
At the end of the pipeline, it applies YAMLFILE to deploy the application
This YAMLFILE does not exist by default from 'appsody init' and is a file the end user adds to the app repo, or places in a separate repo with a pointer. If the file is not found by the pipeline, there is not a useful message in the log about why it failed.
The issue is related to Serviceability/enhancement.

---

@ianpartridge commented on [Tue Aug 13 2019](https://github.com/kabanero-io/kabanero-collection/issues/44#issuecomment-520804608)

From the description above I don't believe that this will require any changes to the format/structure of the collections themselves?  Rather, the changes will be to the operator/pipeline?

If I am correct, shouldn't this issue be against a different repo?

---

@dacleyra commented on [Wed Aug 14 2019](https://github.com/kabanero-io/kabanero-collection/issues/44#issuecomment-521238016)

My thought is that the bash executed here would be a little more complex and echo a useful message if the `find` fails, so that it is apparent in the logs

https://github.com/kabanero-io/kabanero-collection/blob/master/experimental/java-microprofile-0.2.1/appsody-build-task.yaml#L50

---

@kaczyns commented on [Wed Aug 14 2019](https://github.com/kabanero-io/kabanero-collection/issues/44#issuecomment-521242346)

I think this probably goes to the kabanero-pipelines rep, this file:
https://github.com/kabanero-io/kabanero-pipelines/blob/master/pipelines/tasks/appsody-build-task.yaml

**Comment by groeges** [comment]
Moved from the collections repo as this seems to be a pipeline issue / enhancement

**Comment by kvijai82** [comment]
We print the following message if the file doesn't exist now in that step:

          if [ -z "$APP_DEPLOY_YAML" ]; then
            echo "ERROR: app-deploy.yaml not found in project.  Please run appsody deploy --generate-only in your appsody project to generate the app-deploy.yaml and check it into your repo before running the pipeline."
            exit 1
          fi
