### ISSUE TITLE
Serviceability: need error message to indicate the reason why build-task fails

### ISSUE THREAD

**Issue by tam512** [kabanero-io/kabanero-pipelines#63]
Build-task in tekton pipeline fails with message `Unable to fetch log` as in the screen shot below. There is no clue on what caused the failure

<img width="1049" alt="Screen Shot 2019-09-18 at 12 07 02 PM" src="https://user-images.githubusercontent.com/22480038/65170454-4d224680-da0e-11e9-8aea-117017205cce.png">

In order to find a clue for what went wrong, users have to `Rebuild` the same failed job so that the **build-task**'s pod (e.g. njsexpress-webhook-1568760906-r-82409-build-task-4c8z7-pod-aaf0b5)  isrunning again, then describe on the pod and look under `Events` for the clue
```
# oc describe pod njsexpress-webhook-1568760906-r-82409-build-task-4c8z7-pod-aaf0b5
...................
.................................
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  2m (x817 over 47m)  default-scheduler  pod has unbound PersistentVolumeClaims (repeated 2 times)
```
* Note that the *build-task*  pod will disappear once the build-task shows as fail in red in the tekton console. 

We need to show some error messages in the tekton Pipeline logs tab in the console so users know how to fix the problem.

**Comment by aadeshpa** [comment]
We reproduced the issue and found that the result is same as above. We also found that since the `pv.yaml` is missing the pod itself is not started and hence in Tekton Dashboard you do not see the logs of that pod.

We created an issue for Tekton Dashboard team to surface the reason which can be found by 2 ways and it is all explained as part of the below issue. 

https://github.com/tektoncd/dashboard/issues/560

**Comment by aadeshpa** [comment]
To solve this issue actual owner are Tekton Dashboard team. So we can mark current issue as closed and monitor the issue given in above comment under `tektoncd` rpository.
@kvijai82 @tseelbach @marikaj123 @tam512

**Comment by aadeshpa** [comment]
Created a Troubleshooting guide in pipelines repository to show how to find the possible error of pv.yaml persistent volume missing in the cluster.

Please find the pull request created for Troubleshooting guide in our pipelines repo https://github.com/kabanero-io/kabanero-pipelines/pull/68
