### ISSUE TITLE
Write some initial tests for the kabanero-pipelines repo

### ISSUE THREAD

**Issue by smcclem** [kabanero-io/kabanero-pipelines#66]
We obviously need a full fledged Kabanero testing framework for kabanero-pipelines repo, i.e. an environment where we can deploy and run our tests from a travis build environment.  We don't have much of those bits yet:

kabanero-io/roadmap#57

This issue is to write some simple scripts to test the parts we have in the kabanero-pipeline repo today.   The scripts delivered with this issue are intended to be run on an Openshift/OKD environment that has already been provisioned (and the Kabanero operator has been installed, and the collections activated).  

This will help us short term in making sure we have some test coverage on the pipelines in this repo running against all the current Kabanero collections.  As the larger framework is fleshed out in issue kabanero-io/roadmap#57 ,  hopefully we can reuse, or plug this into whatever we end up with longer term.

**Comment by marikaj123** [comment]
@smcclem - is there a target release aiming for the work to complete?
