### ISSUE TITLE
New PVs get created for each pipeline run

### ISSUE THREAD

**Issue by kvijai82** [kabanero-io/kabanero-pipelines#70]
In managed OCP clusters on public cloud, the pipelines provision a new PV for each pipeline run which adds a few minutes to each run.  Understand the storage requirements better for pipelines and document the results.

**Comment by kvijai82** [comment]
Tekton pipelines need a PV to share data across tasks in a pipeline.  We document that the user should create a PV in an OKD cluster.  If that's not there, there is an error message indicating that.  

Looks like in a standard OCP cluster, with dynamic PVs enabled, this requirement is less clear to the user and by default a 20GB PV get created every time a pipeline is kicked off.  Investigate if there is a better out of the box solution here and document it clearly.

**Comment by mnuttall** [comment]
The relevant Tekton information is here: https://github.com/tektoncd/pipeline/blob/master/docs/install.md#how-are-resources-shared-between-tasks
The doc implies that the default size of the PVC can be changed. It also rightly encourages the use of  [Dynamic Volume Provisioning](https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/) in the target cluster. Dynamic Volume Provisioning is the 'better out of the box solution' referred to above.

**Comment by aadeshpa** [comment]
We investigated the OCP cluster in IBM Cloud and figured out how it creates new PV for each pipelinerun.
1. We found that IBM Cloud OCP cluster has default storage class that provisions `classic IBM Cloud Block Storage` where the provisioner is `ibm.io/ibmc-block` and `reclaimPolicy: Delete` so it provisions 20GB block PV for every step in the pipelinerun.
Reference link for more information of IBM Cloud Block Storage: - https://cloud.ibm.com/docs/containers?topic=containers-block_storage
2. Then we tried creating our own custom storage class using same provisioner and tried testing whether that gets used when a PVC request is created. We were able to get it running. So we have correct template of the `storage-class` using `provisioner: ibm.io/ibmc-block` and we have pushed it in our kabanero-pipelines repository.
3. We are also creating a VolumeProvisioning document in same repository. https://github.com/kabanero-io/kabanero-pipelines/tree/cf029b408dde3427464426702f614dd900867bb0/pipelines/docs/VolumeProvisioning.md

Next steps: 
We are waiting to test with latest Tekton that allows to provison on the fly persistent volumes using [ConfigMap](https://github.com/tektoncd/pipeline/blob/master/docs/install.md#how-are-resources-shared-between-tasks) which will point to the `StorageClass` we create.

**Comment by marikaj123** [comment]
Tekton dashboard 0.2.1 and wehooks extension release 0.2.1 will be released in a day or two. Kabanero v0.3.0 will be using Tekton pipelline 0..7.0 with Tekton dashboard 0.2.1 and wehooks extension release 0.2.1 with OCP 4.2.

**Comment by aadeshpa** [comment]
We have created necessary files for using dynamic PV creation through `storageclass` and `configmap` . We are waiting to get Tekton updated that will read the `configmap` and create the PV dynamically.

@kvijai82 : can you confirm if we have steps to get Tekton updated with the latest code which makes use of `configMap` ?

**Comment by aadeshpa** [comment]
pull request that is merged in pipelines repository: https://github.com/kabanero-io/kabanero-pipelines/pull/93
