### ISSUE TITLE
Tekton pipeline default `buildbud` step fails - java springboot2 

### ISSUE THREAD

**Issue by Hemankita** [kabanero-io/kabanero-pipelines#71]
The tekton default `buildbud` step fails at STEP 6.

```  xmlstarlet-1.6.1-1.el7.x86_64             unzip-6.0-41.el8.x86_64              libxslt-1.1.32-3.el8.x86_64              Complete!STEP 4: RUN yum install --disableplugin=subscription-manager -y wget ca-certificatesLast metadata expiration check: 0:00:16 ago on Fri Sep 27 03:36:16 2019.Package ca-certificates-2018.2.24-6.el8.noarch is already installed.Dependencies resolved.================================================================================ Package     Arch          Version                 Repository              Size================================================================================Installing: wget        x86_64        1.19.5-7.el8_0.1        ubi-8-appstream        734 kTransaction Summary================================================================================Install  1 PackageTotal download size: 734 kInstalled size: 2.8 MDownloading Packages:wget-1.19.5-7.el8_0.1.x86_64.rpm                671 kB/s | 734 kB     00:01    --------------------------------------------------------------------------------Total                                           668 kB/s | 734 kB     00:01     Running transaction checkTransaction check succeeded.Running transaction testTransaction test succeeded.Running transaction  Preparing        :                                                        1/1   Installing       : wget-1.19.5-7.el8_0.1.x86_64                           1/1   Running scriptlet: wget-1.19.5-7.el8_0.1.x86_64                           1/1   Verifying        : wget-1.19.5-7.el8_0.1.x86_64                           1/1 Installed products updated.Installed:  wget-1.19.5-7.el8_0.1.x86_64                                                  Complete!STEP 5: ENV JAVA_VERSION 1.8.0_sr5fp37STEP 6: RUN set -eux;    ESUM='51f6600dcc51c238bd4fbed73521e225094d7afa9afa2c8fb35ea78519a71930';    YML_FILE='sdk/linux/x86_64/index.yml';    BASE_URL="https://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/meta/";    wget -q -U UA_IBM_JAVA_Docker -O /tmp/index.yml ${BASE_URL}/${YML_FILE};    JAVA_URL=$(sed -n '/^'${JAVA_VERSION}:'/{n;s/\s*uri:\s//p}'< /tmp/index.yml);    wget -q -U UA_IBM_JAVA_Docker -O /tmp/ibm-java.bin ${JAVA_URL};    echo "${ESUM}  /tmp/ibm-java.bin" | sha256sum -c -;    echo "INSTALLER_UI=silent" > /tmp/response.properties;    echo "USER_INSTALL_DIR=/opt/ibm/java" >> /tmp/response.properties;    echo "LICENSE_ACCEPTED=TRUE" >> /tmp/response.properties;    mkdir -p /opt/ibm;    chmod +x /tmp/ibm-java.bin;    /tmp/ibm-java.bin -i silent -f /tmp/response.properties;    rm -f /tmp/response.properties;    rm -f /tmp/index.yml;    rm -f /tmp/ibm-java.bin;+ ESUM=51f6600dcc51c238bd4fbed73521e225094d7afa9afa2c8fb35ea78519a71930+ YML_FILE=sdk/linux/x86_64/index.yml+ BASE_URL=https://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/meta/+ wget -q -U UA_IBM_JAVA_Docker -O /tmp/index.yml https://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/meta//sdk/linux/x86_64/index.yml++ sed -n '/^1.8.0_sr5fp37:/{n;s/\s*uri:\s//p}'+ JAVA_URL=+ wget -q -U UA_IBM_JAVA_Docker -O /tmp/ibm-java.binwget: missing URLUsage: wget [OPTION]... [URL]...Try `wget --help' for more options.subprocess exited with status 1subprocess exited with status 1error building at STEP "RUN set -eux;    ESUM='51f6600dcc51c238bd4fbed73521e225094d7afa9afa2c8fb35ea78519a71930';    YML_FILE='sdk/linux/x86_64/index.yml';    BASE_URL="https://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/meta/";    wget -q -U UA_IBM_JAVA_Docker -O /tmp/index.yml ${BASE_URL}/${YML_FILE};    JAVA_URL=$(sed -n '/^'${JAVA_VERSION}:'/{n;s/\s*uri:\s//p}'< /tmp/index.yml);    wget -q -U UA_IBM_JAVA_Docker -O /tmp/ibm-java.bin ${JAVA_URL};    echo "${ESUM}  /tmp/ibm-java.bin" | sha256sum -c -;    echo "INSTALLER_UI=silent" > /tmp/response.properties;    echo "USER_INSTALL_DIR=/opt/ibm/java" >> /tmp/response.properties;    echo "LICENSE_ACCEPTED=TRUE" >> /tmp/response.properties;    mkdir -p /opt/ibm;    chmod +x /tmp/ibm-java.bin;    /tmp/ibm-java.bin -i silent -f /tmp/response.properties;    rm -f /tmp/response.properties;    rm -f /tmp/index.yml;    rm -f /tmp/ibm-java.bin;": exit status 1
Step failed```

**Comment by smcclem** [comment]
I am just testing all the latest versions of the operator, collections and the appsody CLI for release 0.2.0.  Just FYI at this point, I haven't see any issues running the java-spring-boot2 pipeline.

**Comment by kvijai82** [comment]
There was an issue in the stack last week.  The JDK it was trying to pull
down was deleted.  I believe that got fixed now.  If you still have issues
with the pipeline, please let us know.

**Comment by kvijai82** [comment]
@Hemankita this is working in our tests now.  Could you please verify and close this issue if it's working for you.

**Comment by Hemankita** [comment]
It is working
