### ISSUE TITLE
Update & test pipelines to work with new tekton release

### ISSUE THREAD

**Issue by kvijai82** [kabanero-io/kabanero-pipelines#75]
The new version of Tekton (0.7) has a syntax change from {} to ().  Update pipelines and tasks to reflect this and test the pipelines with the new version.

**Comment by kvijai82** [comment]
Waiting for new release of Tekton to get cut by 10/2.

**Comment by marikaj123** [comment]
After Tekton releases on Oct-2, the pipeline team will need a couple of days to complete.

**Comment by kvijai82** [comment]
After discussions with @stephenkinder @garypicher @kaczyns we will test the new tekton release when it's available but will not be pulling in the new tekton release in 0.2.0 and will target it for 0.3.0.

**Comment by anneqm** [comment]
The new Tekton release is available now:
tektoncd/pipelines 0.7.0 was released about 2 weeks ago. 
tektoncd/dashboard with webhooks extension 0.2.0 was released earlier today, Oct-2.

**Comment by marikaj123** [comment]
Ann, thank you for the update. It will be included in kabanero 0.3.0. release.

**Comment by anneqm** [comment]
Tekton is in a continuous delivery mode, all fixes will be at the 0.7.0 level for pipeline and 0.2.0 for the dashboard.

**Comment by stephenkinder** [comment]
@anneqm thank you for the reminder.  I think this is the case for many of the dependent projects Kabanero relies on.  We have a new release process that defines an epic for doing normal maintenance upgrades of dependent projects: [#68](https://github.com/kabanero-io/roadmap/issues/68).  I've open a separate issue [#93](https://github.com/kabanero-io/kabanero-foundation/issues/93) to specifically address the upgrade of tekton pipelines to 0.7.0.

**Comment by marikaj123** [comment]
@kvijai82 - For Tekton pipeline 0.7.0, we need to swap the syntax from ${} to $() ?  as a requirement for going up to the 0.7.0 version of the pipeline.

**Comment by anneqm** [comment]
Please note related PR that mentions syntax change: https://github.com/kabanero-io/kabanero-pipelines/pull/73.

**Comment by kvijai82** [comment]
I was able to test the updated pipelines with the tekton 0.7 on OCP 4.2.
