### ISSUE TITLE
Test: multiple namespace support in the Kabanero Operator

### ISSUE THREAD

**Issue by smcclem** [kabanero-io/kabanero-pipelines#77]
https://github.com/kabanero-io/kabanero-operator/issues/196

Pipelines needs to make sure it can deploy an application into any arbitrary namespace, according to the support delivered in issued 196 for the operator.  

This should not have an impact, but we need to verify.

**Comment by smcclem** [comment]
I tested the namespace support with the java-spring-boot2 project.  I added the namespace metadata to my app-deploy.yaml.   The app deploy worked as part of the pipeline run to the correct namespace. However, I did not yet add a target namespace to my kabanero install for the new namespace,  and yet the app was still deployed. This might be a operator bug. 


[root@periapt1 test]# oc get appsody applications
No resources found.
[root@periapt1 test]# oc project production
Now using project "production" on server "https://periapt1.fyre.ibm.com:8443".
[root@periapt1 test]# oc get appsodyapplications
NAME      IMAGE                                       EXPOSED   RECONCILED   AGE
test2     index.docker.io/smcclem/java-spring-boot2   true                   19m
[root@periapt1 test]#

**Comment by smcclem** [comment]
Ok, so the tests pass. The issue in the last comment was wrong.  The appsody operator had not touched the app deployed into my production namespace.  Once I set the target namespace, it all worked. 

[root@periapt1 test]# oc get appsodyapplication --all-namespaces=true
NAMESPACE    NAME       IMAGE                                       EXPOSED   RECONCILED   AGE
kabanero     appsody7   index.docker.io/smcclem/java-microprofile   true      True         8h
production   test2      index.docker.io/smcclem/java-spring-boot2   true      True         9h

**Comment by nastacio** [comment]
See issue #290, hardcoding one target namespace in the application code repository is a workaround, not actual support for multiple namespaces.

The same application cannot be deployed to multiple namespaces, at least not without editing the application code repository right before each deployment, which is not realistic.
