### ISSUE TITLE
Provide documentation on how to test the updated collection pipelines

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-pipelines#78]
1. When a collection is updated how do you make sure that it will still build fine with pipeline. Need some instructions to test it with pipeline before publishing it. 

Below doc has section which needs to be filled
https://github.com/kabanero-io/collections
https://kabanero.io/docs/ref/general/collection-building.html

```
3. Test the pipelines and other components that have been included in the collection within the Kabanero/OpenShift environment.

More details coming.
```

**Comment by marikaj123** [comment]
Please assist in providing the appropriate assignee for the issue

**Comment by jantley-ibm** [comment]
@mtamboli could you add this requirement to issue 56 and close this one?

**Comment by marikaj123** [comment]
@kaczyns - Is there any documentation work pending from your side for this issue?

**Comment by kaczyns** [comment]
I don't think the operator has any doc for this issue.  Unless I don't understand the issue :-)

**Comment by kvijai82** [comment]
@kaczyns @marikaj123 I don't think there is any operator doc work here either.  I will address this issue in https://github.com/kabanero-io/docs/issues/56

**Comment by mtamboli** [comment]
I am closing this one as Vijai is updating in other doc. Will verify there.
