### ISSUE TITLE
Document storage requirements of IBM Cloud OCP's internal Docker registry 

### ISSUE THREAD

**Issue by navidsh** [kabanero-io/kabanero-pipelines#82]
`docker push` into an internal Docker registry of OCP on IKS sometimes fails with `received unexpected HTTP status: 504 Gateway Time-out`. This is due to the low IOPS of the backing storage of the registry's PV.

To get around this problem, users can change IOPS of the existing backing storage device of the PV. See [Changing the size and IOPS of your existing storage device](https://test.cloud.ibm.com/docs/openshift?topic=openshift-file_storage#file_change_storage_configuration) for how to increase the IOPS.

After I upgraded the storage config to the gold tier with higher IOPS, I didn't see the issue: `ibmcloud sl file volume-modify <volume_ID> --new-tier 10`

Since this could be a common issue for users, this should be documented in the common problems doc.

Note that the default config of the registry's PV is the Bronze tier storage class and `20Gi`. Given how big tWAS image sizes, it might be good to also document that users can increase the size of the backing storage while switching storage tier.

**Comment by stephenkinder** [comment]
@bschrammIBM We need to add this guideline to the documentation for running Kabanero in an IKS-managed OCP instance.

**Comment by jantley-ibm** [comment]
Link to PR for review; couldn't add @navidsh or @stevemar as reviewers.
https://github.com/kabanero-io/docs/pull/169

**Comment by kvijai82** [comment]
@aadeshpa could you also please see if our storage & troubleshooting docs in Kabanero should also to reflect this.

**Comment by artberger** [comment]
Just so you know, in response to the usabilla issue that was opened for the Red Hat OpenShift on IBM Cloud docs, we added a troubleshooting topic for this: https://cloud.ibm.com/docs/openshift?topic=openshift-openshift_troubleshoot#roks_timeout_docker

**Comment by aadeshpa** [comment]
> @aadeshpa could you also please see if our storage & troubleshooting docs in Kabanero should also to reflect this.

@kvijai82  Added the troubleshooting steps in our troubleshooting guide.
Pull request: https://github.com/kabanero-io/kabanero-pipelines/pull/122

**Comment by jantley-ibm** [comment]
@navidsh can this issue be closed now?

**Comment by navidsh** [comment]
Doc changes are delivered. Closing this one.
