### ISSUE TITLE
Need a message in the log for validate-collection-is-active pipeline build when it passes

### ISSUE THREAD

**Issue by tam512** [kabanero-io/kabanero-pipelines#85]
- Install Kabanero 0.2.0 rc1
- trigger a tekton pipeline build 
- Look at the Logs for buid-task in step `validate-collection-is-active`, I see `No log available`
Right now the log only displays if this step fails.  Please display a success message when it passes.

**Comment by smcclem** [comment]
https://github.com/kabanero-io/kabanero-pipelines/pull/88

**Comment by smcclem** [comment]
Merged

**Comment by tam512** [comment]
Hi @smcclem I still see this problem with kabanero collection 0.3.4

**Comment by marikaj123** [comment]
According to Scott: The code fix went in, need to build the new docker image and push it to dockerhub.io . kabanero/validate-collection.

**Comment by smcclem** [comment]
Pushed the dockerfile with the fix to dockerhub kabanero/validate-collection
